<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" align="left" /></a><br><br/>This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.

# ![Spark Logo](http://spark-mooc.github.io/web-assets/images/ta_Spark-logo-small.png) + ![Python Logo](http://spark-mooc.github.io/web-assets/images/python-logo-master-v3-TM-flattened_small.png)

# Spark Tutorial: Learning Apache Spark
This tutorial will teach you how to use [Apache Spark](http://spark.apache.org/), a framework for large-scale data processing, within a notebook. Many traditional frameworks were designed to be run on a single computer. However, many datasets today are too large to be stored on a single computer, and even when a dataset can be stored on one computer (such as the datasets in this tutorial), the dataset can often be processed much more quickly using multiple computers.

Spark has efficient implementations of a number of transformations and actions that can be composed together to perform data processing and analysis. Spark excels at distributing these operations across a cluster while abstracting away many of the underlying implementation details. Spark has been designed with a focus on scalability and efficiency. With Spark you can begin developing your solution on your laptop, using a small dataset, and then use that same code to process terabytes or even petabytes across a distributed cluster.
During this tutorial we will cover:
* Part 1: Basic notebook usage and [Python](https://docs.python.org/2/) integration
* Part 2: An introduction to using [Apache Spark](https://spark.apache.org/) with the [PySpark SQL API](http://spark.apache.org/docs/latest/api/python/pyspark.sql.html#pyspark-sql-module) running in a notebook
* Part 3: Using DataFrames and chaining together transformations and actions
* Part 4: Python Lambda functions and User Defined Functions
* Part 5: Additional DataFrame actions
* Part 6: Additional DataFrame transformations
* Part 7: Caching DataFrames and storage options
* Part 8: Debugging Spark applications and lazy evaluation

The following transformations will be covered:
* `select()`, `filter()`, `distinct()`, `dropDuplicates()`, `orderBy()`, `groupBy()`

The following actions will be covered:
* `first()`, `take()`, `count()`, `collect()`, `show()`

Also covered:
* `cache()`, `unpersist()`

Note that, for reference, you can look up the details of these methods in the Spark's [PySpark SQL API](http://spark.apache.org/docs/latest/api/python/pyspark.sql.html#pyspark-sql-module)

## Part 1: Basic notebook usage and [Python](https://docs.python.org/2/) integration

### (1a) Notebook usage
A notebook is comprised of a linear sequence of cells. These cells can contain either markdown or code, but we won't mix both in one cell. When a markdown cell is executed it renders formatted text, images, and links just like HTML in a normal webpage. The text you are reading right now is part of a markdown cell. Python code cells allow you to execute arbitrary Python commands just like in any Python shell. Place your cursor inside the cell below, and press "Shift" + "Enter" to execute the code and advance to the next cell. You can also press "Ctrl" + "Enter" to execute the code and remain in the cell. These commands work the same in both markdown and code cells.

In [1]:
import pyspark

In [2]:
import sys
sys.path

['',
 '/Users/lisurprise/zhichao/bin/god/fudan/lib/spark-2.0.2-bin-hadoop2.7/python/lib/pyspark.zip',
 '/Users/lisurprise/zhichao/bin/god/fudan/lib/spark-2.0.2-bin-hadoop2.7/python/lib/py4j-0.10.3-src.zip',
 '/Users/lisurprise/anaconda2/lib/python27.zip',
 '/Users/lisurprise/anaconda2/lib/python2.7',
 '/Users/lisurprise/anaconda2/lib/python2.7/plat-darwin',
 '/Users/lisurprise/anaconda2/lib/python2.7/plat-mac',
 '/Users/lisurprise/anaconda2/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/lisurprise/anaconda2/lib/python2.7/lib-tk',
 '/Users/lisurprise/anaconda2/lib/python2.7/lib-old',
 '/Users/lisurprise/anaconda2/lib/python2.7/lib-dynload',
 '/Users/lisurprise/anaconda2/lib/python2.7/site-packages',
 '/Users/lisurprise/anaconda2/lib/python2.7/site-packages/Sphinx-1.5.6-py2.7.egg',
 '/Users/lisurprise/anaconda2/lib/python2.7/site-packages/aeosa',
 '/Users/lisurprise/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg',
 '/Users/lisurprise/anaconda2/lib/python2.7/site-packages/IPython/extensions',
 '/Users/lisurprise/.ipython']

In [3]:
from pyspark.sql import SQLContext
from pyspark.context import SparkContext
sc = SparkContext.getOrCreate()
sqlContext = SQLContext(sc)
# Display the type of the Spark sqlContext
type(sqlContext)

pyspark.sql.context.SQLContext

In [4]:
sc.master

u'local[*]'

In [6]:
# This is a Python cell. You can run normal Python code here...
print 'The sum of 1 and 1 is {0}'.format(1+1)

The sum of 1 and 1 is 2

In [7]:
# Here is another Python cell, this time with a variable (x) declaration and an if statement:
x = 42
if x > 40:
    print 'The sum of 1 and 2 is {0}'.format(1+2)

The sum of 1 and 2 is 3

### (1b) Notebook state
As you work through a notebook it is important that you run all of the code cells. The notebook is stateful, which means that variables and their values are retained until the notebook is detached (in Databricks) or the kernel is restarted (in Jupyter notebooks). If you do not run all of the code cells as you proceed through the notebook, your variables will not be properly initialized and later code might fail. You will also need to rerun any cells that you have modified in order for the changes to be available to other cells.

In [10]:
# This cell relies on x being defined already.
# If we didn't run the cells from part (1a) this code would fail.
print x * 2

84

### (1c) Library imports
We can import standard Python libraries ([modules](https://docs.python.org/2/tutorial/modules.html)) the usual way. An `import` statement will import the specified module. In this tutorial and future labs, we will provide any imports that are necessary.

In [8]:
# Import the datetime library
import datetime
print 'This was last run on: {0}'.format(datetime.datetime.now())

This was last run on: 2017-07-18 14:03:17.150665

## Part 2: An introduction to using [Apache Spark](https://spark.apache.org/) with the [PySpark SQL API](http://spark.apache.org/docs/latest/api/python/pyspark.sql.html#pyspark-sql-module) running in a notebook

### Spark Context
In Spark, communication occurs between a driver and executors. The driver has Spark jobs that it needs to run and these jobs are split into tasks that are submitted to the executors for completion. The results from these tasks are delivered back to the driver.

In part 1, we saw that normal Python code can be executed via cells. When using Databricks this code gets executed in the Spark driver's Java Virtual Machine (JVM) and not in an executor's JVM, and when using an Jupyter notebook it is executed within the kernel associated with the notebook. Since no Spark functionality is actually being used, no tasks are launched on the executors.

In order to use Spark and its DataFrame API we will need to use a `SQLContext`. When running Spark, you start a new Spark application by creating a [SparkContext](http://spark.apache.org/docs/latest/api/python/pyspark.html#pyspark.SparkContext). You can then create a [SQLContext](http://spark.apache.org/docs/latest/api/python/pyspark.html#pyspark.SparkContext) from the `SparkContext`. When the `SparkContext` is created, it asks the master for some cores to use to do work. The master sets these cores aside just for you; they won't be used for other applications. When using PySpark Notebook, both a `SparkContext` and a `SQLContext` are created for you automatically. `sc` is your `SparkContext`, and `sqlContext` is your `SQLContext`.

### (2a) Example Cluster
The diagram shows an example cluster, where the slots allocated for an application are outlined in purple. (Note: We're using the term _slots_ here to indicate threads available to perform parallel work for Spark. Spark documentation often refers to these threads as _cores_, which is a confusing term, as the number of slots available on a particular machine does not necessarily have any relationship to the number of physical CPU cores on that machine.) 

You can view the details of your Spark application in the Spark web UI. The web UI is accessible in Databricks by going to "Clusters" and then clicking on the "Spark UI" link for your cluster. In the web UI, under the "Jobs" tab, you can see a list of jobs that have been scheduled or run. It's likely there isn't any thing interesting here yet because we haven't run any jobs, but we'll return to this page later.

At a high level, every Spark application consists of a driver program that launches various parallel operations on executor Java Virtual Machines (JVMs) running either in a cluster or locally on the same machine. In Databricks, "Databricks Shell" is the driver program. When running locally, `pyspark` is the driver program. In all cases, this driver program contains the main loop for the program and creates distributed datasets on the cluster, then applies operations (transformations & actions) to those datasets. Driver programs access Spark through a SparkContext object, which represents a connection to a computing cluster. A Spark SQL context object (`sqlContext`) is the main entry point for Spark DataFrame and SQL functionality. A `SQLContext` can be used to create DataFrames, which allows you to direct the operations on your data.

Try printing out sqlContext to see its type.

<img src="http://spark-mooc.github.io/web-assets/images/cs105x/diagram-2a.png" style="height: 800px;float: right"/>

Note that the type is `HiveContext`. This means we're working with a version of Spark that has Hive support. Compiling Spark with Hive support is a good idea, even if you don't have a Hive metastore. As the [Spark Programming Guide states](http://spark.apache.org/docs/latest/sql-programming-guide.html#starting-point-sqlcontext), a `HiveContext` "provides a superset of the functionality provided by the basic `SQLContext`. Additional features include the ability to write queries using the more complete HiveQL parser, access to Hive UDFs [user-defined functions], and the ability to read data from Hive tables. To use a `HiveContext`, you do not need to have an existing Hive setup, and all of the data sources available to a `SQLContext` are still available."

### (2b) SparkContext attributes 
You can use Python's [dir()](https://docs.python.org/2/library/functions.html?highlight=dir#dir) function to get a list of all the attributes (including methods) accessible through the `sqlContext` object.

In [12]:
# List sqlContext's attributes
dir(sqlContext)

['__class__',
 '__delattr__',
 '__dict__',
 '__doc__',
 '__format__',
 '__getattribute__',
 '__hash__',
 '__init__',
 '__module__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_inferSchema',
 '_instantiatedContext',
 '_jsc',
 '_jsqlContext',
 '_jvm',
 '_sc',
 '_ssql_ctx',
 'cacheTable',
 'clearCache',
 'createDataFrame',
 'createExternalTable',
 'dropTempTable',
 'getConf',
 'getOrCreate',
 'newSession',
 'range',
 'read',
 'readStream',
 'registerDataFrameAsTable',
 'registerFunction',
 'setConf',
 'sparkSession',
 'sql',
 'streams',
 'table',
 'tableNames',
 'tables',
 'udf',
 'uncacheTable']

### (2c) Getting help
Alternatively, you can use Python's [help()](https://docs.python.org/2/library/functions.html?highlight=help#help) function to get an easier to read list of all the attributes, including examples, that the `sqlContext` object has.

In [13]:
help(sqlContext)

Help on SQLContext in module pyspark.sql.context object:

class SQLContext(__builtin__.object)
 |  The entry point for working with structured data (rows and columns) in Spark, in Spark 1.x.
 |
 |  As of Spark 2.0, this is replaced by :class:`SparkSession`. However, we are keeping the class
 |  here for backward compatibility.
 |
 |  A SQLContext can be used create :class:`DataFrame`, register :class:`DataFrame` as
 |  tables, execute SQL over tables, cache tables, and read parquet files.
 |
 |  :param sparkContext: The :class:`SparkContext` backing this SQLContext.
 |  :param sparkSession: The :class:`SparkSession` around which this SQLContext wraps.
 |  :param jsqlContext: An optional JVM Scala SQLContext. If set, we do not instantiate a new
 |      SQLContext in the JVM, instead we make all calls to this object.
 |
 |  Methods defined here:
 |
 |  __init__(self, sparkContext, sparkSession=None, jsqlContext=None)
 |      Creates a new SQLContext.
 |
 |      >>> from datetime import datetime
 |      >>> sqlContext = SQLContext(sc)
 |      >>> allTypes = sc.parallelize([Row(i=1, s="string", d=1.0, l=1,
 |      ...     b=True, list=[1, 2, 3], dict={"s": 0}, row=Row(a=1),
 |      ...     time=datetime(2014, 8, 1, 14, 1, 5))])
 |      >>> df = allTypes.toDF()
 |      >>> df.createOrReplaceTempView("allTypes")
 |      >>> sqlContext.sql('select i+1, d+1, not b, list[1], dict["s"], time, row.a '
 |      ...            'from allTypes where b and i > 0').collect()
 |      [Row((i + CAST(1 AS BIGINT))=2, (d + CAST(1 AS DOUBLE))=2.0, (NOT b)=False, list[1]=2,             dict[s]=0, time=datetime.datetime(2014, 8, 1, 14, 1, 5), a=1)]
 |      >>> df.rdd.map(lambda x: (x.i, x.s, x.d, x.l, x.b, x.time, x.row.a, x.list)).collect()
 |      [(1, u'string', 1.0, 1, True, datetime.datetime(2014, 8, 1, 14, 1, 5), 1, [1, 2, 3])]
 |
 |  cacheTable(self, tableName)
 |      Caches the specified table in-memory.
 |
 |      .. versionadded:: 1.0
 |
 |  clearCache(self)
 |      Removes all cached tables from the in-memory cache.
 |
 |      .. versionadded:: 1.3
 |
 |  createDataFrame(self, data, schema=None, samplingRatio=None, verifySchema=True)
 |      Creates a :class:`DataFrame` from an :class:`RDD`, a list or a :class:`pandas.DataFrame`.
 |
 |      When ``schema`` is a list of column names, the type of each column
 |      will be inferred from ``data``.
 |
 |      When ``schema`` is ``None``, it will try to infer the schema (column names and types)
 |      from ``data``, which should be an RDD of :class:`Row`,
 |      or :class:`namedtuple`, or :class:`dict`.
 |
 |      When ``schema`` is :class:`pyspark.sql.types.DataType` or
 |      :class:`pyspark.sql.types.StringType`, it must match the
 |      real data, or an exception will be thrown at runtime. If the given schema is not
 |      :class:`pyspark.sql.types.StructType`, it will be wrapped into a
 |      :class:`pyspark.sql.types.StructType` as its only field, and the field name will be "value",
 |      each record will also be wrapped into a tuple, which can be converted to row later.
 |
 |      If schema inference is needed, ``samplingRatio`` is used to determined the ratio of
 |      rows used for schema inference. The first row will be used if ``samplingRatio`` is ``None``.
 |
 |      :param data: an RDD of any kind of SQL data representation(e.g. :class:`Row`,
 |          :class:`tuple`, ``int``, ``boolean``, etc.), or :class:`list`, or
 |          :class:`pandas.DataFrame`.
 |      :param schema: a :class:`pyspark.sql.types.DataType` or a
 |          :class:`pyspark.sql.types.StringType` or a list of
 |          column names, default is None.  The data type string format equals to
 |          :class:`pyspark.sql.types.DataType.simpleString`, except that top level struct type can
 |          omit the ``struct<>`` and atomic types use ``typeName()`` as their format, e.g. use
 |          ``byte`` instead of ``tinyint`` for :class:`pyspark.sql.types.ByteType`.
 |          We can also use ``int`` as a short name for :class:`pyspark.sql.types.IntegerType`.
 |      :param samplingRatio: the sample ratio of rows used for inferring
 |      :param verifySchema: verify data types of every row against schema.
 |      :return: :class:`DataFrame`
 |
 |      .. versionchanged:: 2.0
 |         The ``schema`` parameter can be a :class:`pyspark.sql.types.DataType` or a
 |         :class:`pyspark.sql.types.StringType` after 2.0.
 |         If it's not a :class:`pyspark.sql.types.StructType`, it will be wrapped into a
 |         :class:`pyspark.sql.types.StructType` and each record will also be wrapped into a tuple.
 |
 |      .. versionchanged:: 2.0.1
 |         Added verifySchema.
 |
 |      >>> l = [('Alice', 1)]
 |      >>> sqlContext.createDataFrame(l).collect()
 |      [Row(_1=u'Alice', _2=1)]
 |      >>> sqlContext.createDataFrame(l, ['name', 'age']).collect()
 |      [Row(name=u'Alice', age=1)]
 |
 |      >>> d = [{'name': 'Alice', 'age': 1}]
 |      >>> sqlContext.createDataFrame(d).collect()
 |      [Row(age=1, name=u'Alice')]
 |
 |      >>> rdd = sc.parallelize(l)
 |      >>> sqlContext.createDataFrame(rdd).collect()
 |      [Row(_1=u'Alice', _2=1)]
 |      >>> df = sqlContext.createDataFrame(rdd, ['name', 'age'])
 |      >>> df.collect()
 |      [Row(name=u'Alice', age=1)]
 |
 |      >>> from pyspark.sql import Row
 |      >>> Person = Row('name', 'age')
 |      >>> person = rdd.map(lambda r: Person(*r))
 |      >>> df2 = sqlContext.createDataFrame(person)
 |      >>> df2.collect()
 |      [Row(name=u'Alice', age=1)]
 |
 |      >>> from pyspark.sql.types import *
 |      >>> schema = StructType([
 |      ...    StructField("name", StringType(), True),
 |      ...    StructField("age", IntegerType(), True)])
 |      >>> df3 = sqlContext.createDataFrame(rdd, schema)
 |      >>> df3.collect()
 |      [Row(name=u'Alice', age=1)]
 |
 |      >>> sqlContext.createDataFrame(df.toPandas()).collect()  # doctest: +SKIP
 |      [Row(name=u'Alice', age=1)]
 |      >>> sqlContext.createDataFrame(pandas.DataFrame([[1, 2]])).collect()  # doctest: +SKIP
 |      [Row(0=1, 1=2)]
 |
 |      >>> sqlContext.createDataFrame(rdd, "a: string, b: int").collect()
 |      [Row(a=u'Alice', b=1)]
 |      >>> rdd = rdd.map(lambda row: row[1])
 |      >>> sqlContext.createDataFrame(rdd, "int").collect()
 |      [Row(value=1)]
 |      >>> sqlContext.createDataFrame(rdd, "boolean").collect() # doctest: +IGNORE_EXCEPTION_DETAIL
 |      Traceback (most recent call last):
 |          ...
 |      Py4JJavaError: ...
 |
 |      .. versionadded:: 1.3
 |
 |  createExternalTable(self, tableName, path=None, source=None, schema=None, **options)
 |      Creates an external table based on the dataset in a data source.
 |
 |      It returns the DataFrame associated with the external table.
 |
 |      The data source is specified by the ``source`` and a set of ``options``.
 |      If ``source`` is not specified, the default data source configured by
 |      ``spark.sql.sources.default`` will be used.
 |
 |      Optionally, a schema can be provided as the schema of the returned :class:`DataFrame` and
 |      created external table.
 |
 |      :return: :class:`DataFrame`
 |
 |      .. versionadded:: 1.3
 |
 |  dropTempTable(self, tableName)
 |      Remove the temp table from catalog.
 |
 |      >>> sqlContext.registerDataFrameAsTable(df, "table1")
 |      >>> sqlContext.dropTempTable("table1")
 |
 |      .. versionadded:: 1.6
 |
 |  getConf(self, key, defaultValue=None)
 |      Returns the value of Spark SQL configuration property for the given key.
 |
 |      If the key is not set and defaultValue is not None, return
 |      defaultValue. If the key is not set and defaultValue is None, return
 |      the system default value.
 |
 |      >>> sqlContext.getConf("spark.sql.shuffle.partitions")
 |      u'200'
 |      >>> sqlContext.getConf("spark.sql.shuffle.partitions", u"10")
 |      u'10'
 |      >>> sqlContext.setConf("spark.sql.shuffle.partitions", u"50")
 |      >>> sqlContext.getConf("spark.sql.shuffle.partitions", u"10")
 |      u'50'
 |
 |      .. versionadded:: 1.3
 |
 |  newSession(self)
 |      Returns a new SQLContext as new session, that has separate SQLConf,
 |      registered temporary views and UDFs, but shared SparkContext and
 |      table cache.
 |
 |      .. versionadded:: 1.6
 |
 |  range(self, start, end=None, step=1, numPartitions=None)
 |      Create a :class:`DataFrame` with single :class:`pyspark.sql.types.LongType` column named
 |      ``id``, containing elements in a range from ``start`` to ``end`` (exclusive) with
 |      step value ``step``.
 |
 |      :param start: the start value
 |      :param end: the end value (exclusive)
 |      :param step: the incremental step (default: 1)
 |      :param numPartitions: the number of partitions of the DataFrame
 |      :return: :class:`DataFrame`
 |
 |      >>> sqlContext.range(1, 7, 2).collect()
 |      [Row(id=1), Row(id=3), Row(id=5)]
 |
 |      If only one argument is specified, it will be used as the end value.
 |
 |      >>> sqlContext.range(3).collect()
 |      [Row(id=0), Row(id=1), Row(id=2)]
 |
 |      .. versionadded:: 1.4
 |
 |  registerDataFrameAsTable(self, df, tableName)
 |      Registers the given :class:`DataFrame` as a temporary table in the catalog.
 |
 |      Temporary tables exist only during the lifetime of this instance of :class:`SQLContext`.
 |
 |      >>> sqlContext.registerDataFrameAsTable(df, "table1")
 |
 |      .. versionadded:: 1.3
 |
 |  registerFunction(self, name, f, returnType=StringType)
 |      Registers a python function (including lambda function) as a UDF
 |      so it can be used in SQL statements.
 |
 |      In addition to a name and the function itself, the return type can be optionally specified.
 |      When the return type is not given it default to a string and conversion will automatically
 |      be done.  For any other return type, the produced object must match the specified type.
 |
 |      :param name: name of the UDF
 |      :param f: python function
 |      :param returnType: a :class:`pyspark.sql.types.DataType` object
 |
 |      >>> sqlContext.registerFunction("stringLengthString", lambda x: len(x))
 |      >>> sqlContext.sql("SELECT stringLengthString('test')").collect()
 |      [Row(stringLengthString(test)=u'4')]
 |
 |      >>> from pyspark.sql.types import IntegerType
 |      >>> sqlContext.registerFunction("stringLengthInt", lambda x: len(x), IntegerType())
 |      >>> sqlContext.sql("SELECT stringLengthInt('test')").collect()
 |      [Row(stringLengthInt(test)=4)]
 |
 |      >>> from pyspark.sql.types import IntegerType
 |      >>> sqlContext.udf.register("stringLengthInt", lambda x: len(x), IntegerType())
 |      >>> sqlContext.sql("SELECT stringLengthInt('test')").collect()
 |      [Row(stringLengthInt(test)=4)]
 |
 |      .. versionadded:: 1.2
 |
 |  setConf(self, key, value)
 |      Sets the given Spark SQL configuration property.
 |
 |      .. versionadded:: 1.3
 |
 |  sql(self, sqlQuery)
 |      Returns a :class:`DataFrame` representing the result of the given query.
 |
 |      :return: :class:`DataFrame`
 |
 |      >>> sqlContext.registerDataFrameAsTable(df, "table1")
 |      >>> df2 = sqlContext.sql("SELECT field1 AS f1, field2 as f2 from table1")
 |      >>> df2.collect()
 |      [Row(f1=1, f2=u'row1'), Row(f1=2, f2=u'row2'), Row(f1=3, f2=u'row3')]
 |
 |      .. versionadded:: 1.0
 |
 |  table(self, tableName)
 |      Returns the specified table as a :class:`DataFrame`.
 |
 |      :return: :class:`DataFrame`
 |
 |      >>> sqlContext.registerDataFrameAsTable(df, "table1")
 |      >>> df2 = sqlContext.table("table1")
 |      >>> sorted(df.collect()) == sorted(df2.collect())
 |      True
 |
 |      .. versionadded:: 1.0
 |
 |  tableNames(self, dbName=None)
 |      Returns a list of names of tables in the database ``dbName``.
 |
 |      :param dbName: string, name of the database to use. Default to the current database.
 |      :return: list of table names, in string
 |
 |      >>> sqlContext.registerDataFrameAsTable(df, "table1")
 |      >>> "table1" in sqlContext.tableNames()
 |      True
 |      >>> "table1" in sqlContext.tableNames("default")
 |      True
 |
 |      .. versionadded:: 1.3
 |
 |  tables(self, dbName=None)
 |      Returns a :class:`DataFrame` containing names of tables in the given database.
 |
 |      If ``dbName`` is not specified, the current database will be used.
 |
 |      The returned DataFrame has two columns: ``tableName`` and ``isTemporary``
 |      (a column with :class:`BooleanType` indicating if a table is a temporary one or not).
 |
 |      :param dbName: string, name of the database to use.
 |      :return: :class:`DataFrame`
 |
 |      >>> sqlContext.registerDataFrameAsTable(df, "table1")
 |      >>> df2 = sqlContext.tables()
 |      >>> df2.filter("tableName = 'table1'").first()
 |      Row(tableName=u'table1', isTemporary=True)
 |
 |      .. versionadded:: 1.3
 |
 |  uncacheTable(self, tableName)
 |      Removes the specified table from the in-memory cache.
 |
 |      .. versionadded:: 1.0
 |
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |
 |  getOrCreate(cls, sc) from __builtin__.type
 |      Get the existing SQLContext or create a new one with given SparkContext.
 |
 |      :param sc: SparkContext
 |
 |      .. versionadded:: 1.6
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)
 |
 |  read
 |      Returns a :class:`DataFrameReader` that can be used to read data
 |      in as a :class:`DataFrame`.
 |
 |      :return: :class:`DataFrameReader`
 |
 |      .. versionadded:: 1.4
 |
 |  readStream
 |      Returns a :class:`DataStreamReader` that can be used to read data streams
 |      as a streaming :class:`DataFrame`.
 |
 |      .. note:: Experimental.
 |
 |      :return: :class:`DataStreamReader`
 |
 |      >>> text_sdf = sqlContext.readStream.text(tempfile.mkdtemp())
 |      >>> text_sdf.isStreaming
 |      True
 |
 |      .. versionadded:: 2.0
 |
 |  streams
 |      Returns a :class:`StreamingQueryManager` that allows managing all the
 |      :class:`StreamingQuery` StreamingQueries active on `this` context.
 |
 |      .. note:: Experimental.
 |
 |      .. versionadded:: 2.0
 |
 |  udf
 |      Returns a :class:`UDFRegistration` for UDF registration.
 |
 |      :return: :class:`UDFRegistration`
 |
 |      .. versionadded:: 1.3.1

Outside of `pyspark` or a notebook, `SQLContext` is created from the lower-level `SparkContext`, which is usually used to create Resilient Distributed Datasets (RDDs). An RDD is the way Spark actually represents data internally; DataFrames are actually implemented in terms of RDDs.

While you can interact directly with RDDs, DataFrames are preferred. They're generally faster, and they perform the same no matter what language (Python, R, Scala or Java) you use with Spark.

In this course, we'll be using DataFrames, so we won't be interacting directly with the Spark Context object very much. However, it's worth knowing that inside `pyspark` or a notebook, you already have an existing `SparkContext` in the `sc` variable. One simple thing we can do with `sc` is check the version of Spark we're using:

In [14]:
# After reading the help we've decided we want to use sc.version to see what version of Spark we are running
sc.version

u'2.0.2'

In [15]:
# Help can be used on any Python object
help(map)

Help on built-in function map in module __builtin__:

map(...)
    map(function, sequence[, sequence, ...]) -> list

    Return a list of the results of applying the function to the items of
    the argument sequence(s).  If more than one sequence is given, the
    function is called with an argument list consisting of the corresponding
    item of each sequence, substituting None for missing values when not all
    sequences have the same length.  If the function is None, return a list of
    the items of the sequence (or a list of tuples if more than one sequence).

## Part 3: Using DataFrames and chaining together transformations and actions

### Working with your first DataFrames

In Spark, we first create a base [DataFrame](http://spark.apache.org/docs/latest/api/python/pyspark.sql.html#pyspark.sql.DataFrame). We can then apply one or more transformations to that base DataFrame. _A DataFrame is immutable, so once it is created, it cannot be changed._ As a result, each transformation creates a new DataFrame. Finally, we can apply one or more actions to the DataFrames.

> Note that Spark uses lazy evaluation, so transformations are not actually executed until an action occurs.

We will perform several exercises to obtain a better understanding of DataFrames:
* Create a Python collection of 10,000 integers
* Create a Spark DataFrame from that collection
* Subtract one from each value using `map`
* Perform action `collect` to view results
* Perform action `count` to view counts
* Apply transformation `filter` and view results with `collect`
* Learn about lambda functions
* Explore how lazy evaluation works and the debugging challenges that it introduces

A DataFrame consists of a series of `Row` objects; each `Row` object has a set of named columns. You can think of a DataFrame as modeling a table, though the data source being processed does not have to be a table.

More formally, a DataFrame must have a schema, which means it must consist of columns, each of which has a _name_ and a _type_. Some data sources have schemas built into them. Examples include RDBMS databases, Parquet files, and NoSQL databases like Cassandra. Other data sources don't have computer-readable schemas, but you can often apply a schema programmatically.

### (3a) Create a Python collection of 10,000 people
1. We will use a third-party Python testing library called [fake-factory](https://pypi.python.org/pypi/fake-factory/0.5.3) to create a collection of fake person records.
2. Installation:
 pip install Faker

In [5]:
from faker import Factory
fake = Factory.create()
fake.seed(4321)
fake.name()

u'Jason Brown'

We're going to use this factory to create a collection of randomly generated people records. In the next section, we'll turn that collection into a DataFrame. We'll use the Spark `Row` class, because that will help us define the Spark DataFrame schema. There are other ways to define schemas, though; see the Spark Programming Guide's discussion of [schema inference](http://spark.apache.org/docs/latest/sql-programming-guide.html#inferring-the-schema-using-reflection) for more information. (For instance, we could also use a Python `namedtuple`.)

In [6]:
# Each entry consists of last_name, first_name, ssn, job, and age (at least 1)
from pyspark.sql import Row
def fake_entry():
    name = fake.name().split()
    return Row(name[1], name[0], fake.ssn(), fake.job(), abs(2017-fake.date_time().year)+1)

In [7]:
# Create a helper function to call a function repeatedly
def repeat(times, func, *args, **kwargs):
    for _ in xrange(times):
        yield func(*args, **kwargs)

In [8]:
data = list(repeat(10000, fake_entry))

In [10]:
data[0][0]

u'Stein'

`data` is just a normal Python list, containing Spark SQL `Row` objects. Let's look at the first item in the list:

In [11]:
data[0][0],data[0][1],data[0][2],data[0][3],data[0][4]

(u'Stein', u'Jacob', u'039-19-0531', 'Education officer, community', 20)

We can check the size of the list using the Python `len()` function.

In [12]:
len(data)

10000

### (3b) Distributed data and using a collection to create a DataFrame 
In Spark, datasets are represented as a list of entries, where the list is broken up into many different partitions that are each stored on a different machine. Each partition holds a unique subset of the entries in the list. Spark calls datasets that it stores "Resilient Distributed Datasets" (RDDs). Even DataFrames are ultimately represented as RDDs, with additional meta-data.

One of the defining features of Spark, compared to other data analytics frameworks (e.g., Hadoop), is that it stores data in memory rather than on disk. This allows Spark applications to run much more quickly, because they are not slowed down by needing to read data from disk. The figure to the right illustrates how Spark breaks a list of data entries into partitions that are each stored in memory on a worker.

<img src="http://spark-mooc.github.io/web-assets/images/cs105x/diagram-3b.png" style="width: 900px; float: right; margin: 5px"/>

To create the DataFrame, we'll use `sqlContext.createDataFrame()`, and we'll pass our array of data in as an argument to that function. Spark will create a new set of input data based on data that is passed in. A DataFrame requires a _schema_, which is a list of columns, where each column has a name and a type. Our list of data has elements with types (mostly strings, but one integer). We'll supply the rest of the schema and the column names as the second argument to `createDataFrame()`.

Let's view the help for `createDataFrame()`.

In [13]:
help(sqlContext.createDataFrame)

Help on method createDataFrame in module pyspark.sql.context:

createDataFrame(self, data, schema=None, samplingRatio=None, verifySchema=True) method of pyspark.sql.context.SQLContext instance
    Creates a :class:`DataFrame` from an :class:`RDD`, a list or a :class:`pandas.DataFrame`.

    When ``schema`` is a list of column names, the type of each column
    will be inferred from ``data``.

    When ``schema`` is ``None``, it will try to infer the schema (column names and types)
    from ``data``, which should be an RDD of :class:`Row`,
    or :class:`namedtuple`, or :class:`dict`.

    When ``schema`` is :class:`pyspark.sql.types.DataType` or
    :class:`pyspark.sql.types.StringType`, it must match the
    real data, or an exception will be thrown at runtime. If the given schema is not
    :class:`pyspark.sql.types.StructType`, it will be wrapped into a
    :class:`pyspark.sql.types.StructType` as its only field, and the field name will be "value",
    each record will also be wrapped into a tuple, which can be converted to row later.

    If schema inference is needed, ``samplingRatio`` is used to determined the ratio of
    rows used for schema inference. The first row will be used if ``samplingRatio`` is ``None``.

    :param data: an RDD of any kind of SQL data representation(e.g. :class:`Row`,
        :class:`tuple`, ``int``, ``boolean``, etc.), or :class:`list`, or
        :class:`pandas.DataFrame`.
    :param schema: a :class:`pyspark.sql.types.DataType` or a
        :class:`pyspark.sql.types.StringType` or a list of
        column names, default is None.  The data type string format equals to
        :class:`pyspark.sql.types.DataType.simpleString`, except that top level struct type can
        omit the ``struct<>`` and atomic types use ``typeName()`` as their format, e.g. use
        ``byte`` instead of ``tinyint`` for :class:`pyspark.sql.types.ByteType`.
        We can also use ``int`` as a short name for :class:`pyspark.sql.types.IntegerType`.
    :param samplingRatio: the sample ratio of rows used for inferring
    :param verifySchema: verify data types of every row against schema.
    :return: :class:`DataFrame`

    .. versionchanged:: 2.0
       The ``schema`` parameter can be a :class:`pyspark.sql.types.DataType` or a
       :class:`pyspark.sql.types.StringType` after 2.0.
       If it's not a :class:`pyspark.sql.types.StructType`, it will be wrapped into a
       :class:`pyspark.sql.types.StructType` and each record will also be wrapped into a tuple.

    .. versionchanged:: 2.0.1
       Added verifySchema.

    >>> l = [('Alice', 1)]
    >>> sqlContext.createDataFrame(l).collect()
    [Row(_1=u'Alice', _2=1)]
    >>> sqlContext.createDataFrame(l, ['name', 'age']).collect()
    [Row(name=u'Alice', age=1)]

    >>> d = [{'name': 'Alice', 'age': 1}]
    >>> sqlContext.createDataFrame(d).collect()
    [Row(age=1, name=u'Alice')]

    >>> rdd = sc.parallelize(l)
    >>> sqlContext.createDataFrame(rdd).collect()
    [Row(_1=u'Alice', _2=1)]
    >>> df = sqlContext.createDataFrame(rdd, ['name', 'age'])
    >>> df.collect()
    [Row(name=u'Alice', age=1)]

    >>> from pyspark.sql import Row
    >>> Person = Row('name', 'age')
    >>> person = rdd.map(lambda r: Person(*r))
    >>> df2 = sqlContext.createDataFrame(person)
    >>> df2.collect()
    [Row(name=u'Alice', age=1)]

    >>> from pyspark.sql.types import *
    >>> schema = StructType([
    ...    StructField("name", StringType(), True),
    ...    StructField("age", IntegerType(), True)])
    >>> df3 = sqlContext.createDataFrame(rdd, schema)
    >>> df3.collect()
    [Row(name=u'Alice', age=1)]

    >>> sqlContext.createDataFrame(df.toPandas()).collect()  # doctest: +SKIP
    [Row(name=u'Alice', age=1)]
    >>> sqlContext.createDataFrame(pandas.DataFrame([[1, 2]])).collect()  # doctest: +SKIP
    [Row(0=1, 1=2)]

    >>> sqlContext.createDataFrame(rdd, "a: string, b: int").collect()
    [Row(a=u'Alice', b=1)]
    >>> rdd = rdd.map(lambda row: row[1])
    >>> sqlContext.createDataFrame(rdd, "int").collect()
    [Row(value=1)]
    >>> sqlContext.createDataFrame(rdd, "boolean").collect() # doctest: +IGNORE_EXCEPTION_DETAIL
    Traceback (most recent call last):
        ...
    Py4JJavaError: ...

    .. versionadded:: 1.3

In [14]:
dataDF = sqlContext.createDataFrame(data,('last_name', 'first_name','ssn','occupation','age'))

Let's see what type `sqlContext.createDataFrame()` returned.

In [15]:
print 'type of dataDF: {0}'.format(type(dataDF))

type of dataDF: <class 'pyspark.sql.dataframe.DataFrame'>

Let's take a look at the DataFrame's schema and some of its rows.

In [16]:
dataDF.printSchema()
dataDF.show(5)

root
 |-- last_name: string (nullable = true)
 |-- first_name: string (nullable = true)
 |-- ssn: string (nullable = true)
 |-- occupation: string (nullable = true)
 |-- age: long (nullable = true)

+---------+----------+-----------+--------------------+---+
|last_name|first_name|        ssn|          occupation|age|
+---------+----------+-----------+--------------------+---+
|    Stein|     Jacob|039-19-0531|Education officer...| 20|
| Hamilton|     Tommy|824-45-1140|Chief Operating O...| 37|
|  Chapman|   Deborah|735-56-4346|Copywriter, adver...| 20|
|    Moody|     David|382-11-7793|Designer, multimedia| 39|
|  Oconnor|   Michael|356-45-3733|    Paediatric nurse| 28|
+---------+----------+-----------+--------------------+---+
only showing top 5 rows

We can register the newly created DataFrame as a named table, using the `registerDataFrameAsTable()` method.

In [17]:
sqlContext.registerDataFrameAsTable(dataDF, 'dataframe')

What methods can we call on this DataFrame?

In [18]:
help(dataDF)
dataDF.explain(extended=True)
sqlContext.sql("select * from dataframe")

Help on DataFrame in module pyspark.sql.dataframe object:

class DataFrame(__builtin__.object)
 |  A distributed collection of data grouped into named columns.
 |
 |  A :class:`DataFrame` is equivalent to a relational table in Spark SQL,
 |  and can be created using various functions in :class:`SQLContext`::
 |
 |      people = sqlContext.read.parquet("...")
 |
 |  Once created, it can be manipulated using the various domain-specific-language
 |  (DSL) functions defined in: :class:`DataFrame`, :class:`Column`.
 |
 |  To select a column from the data frame, use the apply method::
 |
 |      ageCol = people.age
 |
 |  A more concrete example::
 |
 |      # To create DataFrame using SQLContext
 |      people = sqlContext.read.parquet("...")
 |      department = sqlContext.read.parquet("...")
 |
 |      people.filter(people.age > 30).join(department, people.deptId == department.id) \
 |        .groupBy(department.name, "gender").agg({"salary": "avg", "age": "max"})
 |
 |  .. versionadded:: 1.3
 |
 |  Methods defined here:
 |
 |  __getattr__(self, name)
 |      Returns the :class:`Column` denoted by ``name``.
 |
 |      >>> df.select(df.age).collect()
 |      [Row(age=2), Row(age=5)]
 |
 |      .. versionadded:: 1.3
 |
 |  __getitem__(self, item)
 |      Returns the column as a :class:`Column`.
 |
 |      >>> df.select(df['age']).collect()
 |      [Row(age=2), Row(age=5)]
 |      >>> df[ ["name", "age"]].collect()
 |      [Row(name=u'Alice', age=2), Row(name=u'Bob', age=5)]
 |      >>> df[ df.age > 3 ].collect()
 |      [Row(age=5, name=u'Bob')]
 |      >>> df[df[0] > 3].collect()
 |      [Row(age=5, name=u'Bob')]
 |
 |      .. versionadded:: 1.3
 |
 |  __init__(self, jdf, sql_ctx)
 |
 |  __repr__(self)
 |
 |  agg(self, *exprs)
 |      Aggregate on the entire :class:`DataFrame` without groups
 |      (shorthand for ``df.groupBy.agg()``).
 |
 |      >>> df.agg({"age": "max"}).collect()
 |      [Row(max(age)=5)]
 |      >>> from pyspark.sql import functions as F
 |      >>> df.agg(F.min(df.age)).collect()
 |      [Row(min(age)=2)]
 |
 |      .. versionadded:: 1.3
 |
 |  alias(self, alias)
 |      Returns a new :class:`DataFrame` with an alias set.
 |
 |      >>> from pyspark.sql.functions import *
 |      >>> df_as1 = df.alias("df_as1")
 |      >>> df_as2 = df.alias("df_as2")
 |      >>> joined_df = df_as1.join(df_as2, col("df_as1.name") == col("df_as2.name"), 'inner')
 |      >>> joined_df.select("df_as1.name", "df_as2.name", "df_as2.age").collect()
 |      [Row(name=u'Bob', name=u'Bob', age=5), Row(name=u'Alice', name=u'Alice', age=2)]
 |
 |      .. versionadded:: 1.3
 |
 |  approxQuantile(self, col, probabilities, relativeError)
 |      Calculates the approximate quantiles of a numerical column of a
 |      DataFrame.
 |
 |      The result of this algorithm has the following deterministic bound:
 |      If the DataFrame has N elements and if we request the quantile at
 |      probability `p` up to error `err`, then the algorithm will return
 |      a sample `x` from the DataFrame so that the *exact* rank of `x` is
 |      close to (p * N). More precisely,
 |
 |        floor((p - err) * N) <= rank(x) <= ceil((p + err) * N).
 |
 |      This method implements a variation of the Greenwald-Khanna
 |      algorithm (with some speed optimizations). The algorithm was first
 |      present in [[http://dx.doi.org/10.1145/375663.375670
 |      Space-efficient Online Computation of Quantile Summaries]]
 |      by Greenwald and Khanna.
 |
 |      :param col: the name of the numerical column
 |      :param probabilities: a list of quantile probabilities
 |        Each number must belong to [0, 1].
 |        For example 0 is the minimum, 0.5 is the median, 1 is the maximum.
 |      :param relativeError:  The relative target precision to achieve
 |        (>= 0). If set to zero, the exact quantiles are computed, which
 |        could be very expensive. Note that values greater than 1 are
 |        accepted but give the same result as 1.
 |      :return:  the approximate quantiles at the given probabilities
 |
 |      .. versionadded:: 2.0
 |
 |  cache(self)
 |      Persists with the default storage level (C{MEMORY_ONLY}).
 |
 |      .. versionadded:: 1.3
 |
 |  coalesce(self, numPartitions)
 |      Returns a new :class:`DataFrame` that has exactly `numPartitions` partitions.
 |
 |      Similar to coalesce defined on an :class:`RDD`, this operation results in a
 |      narrow dependency, e.g. if you go from 1000 partitions to 100 partitions,
 |      there will not be a shuffle, instead each of the 100 new partitions will
 |      claim 10 of the current partitions.
 |
 |      >>> df.coalesce(1).rdd.getNumPartitions()
 |      1
 |
 |      .. versionadded:: 1.4
 |
 |  collect(self)
 |      Returns all the records as a list of :class:`Row`.
 |
 |      >>> df.collect()
 |      [Row(age=2, name=u'Alice'), Row(age=5, name=u'Bob')]
 |
 |      .. versionadded:: 1.3
 |
 |  corr(self, col1, col2, method=None)
 |      Calculates the correlation of two columns of a DataFrame as a double value.
 |      Currently only supports the Pearson Correlation Coefficient.
 |      :func:`DataFrame.corr` and :func:`DataFrameStatFunctions.corr` are aliases of each other.
 |
 |      :param col1: The name of the first column
 |      :param col2: The name of the second column
 |      :param method: The correlation method. Currently only supports "pearson"
 |
 |      .. versionadded:: 1.4
 |
 |  count(self)
 |      Returns the number of rows in this :class:`DataFrame`.
 |
 |      >>> df.count()
 |      2
 |
 |      .. versionadded:: 1.3
 |
 |  cov(self, col1, col2)
 |      Calculate the sample covariance for the given columns, specified by their names, as a
 |      double value. :func:`DataFrame.cov` and :func:`DataFrameStatFunctions.cov` are aliases.
 |
 |      :param col1: The name of the first column
 |      :param col2: The name of the second column
 |
 |      .. versionadded:: 1.4
 |
 |  createOrReplaceTempView(self, name)
 |      Creates or replaces a temporary view with this DataFrame.
 |
 |      The lifetime of this temporary table is tied to the :class:`SparkSession`
 |      that was used to create this :class:`DataFrame`.
 |
 |      >>> df.createOrReplaceTempView("people")
 |      >>> df2 = df.filter(df.age > 3)
 |      >>> df2.createOrReplaceTempView("people")
 |      >>> df3 = spark.sql("select * from people")
 |      >>> sorted(df3.collect()) == sorted(df2.collect())
 |      True
 |      >>> spark.catalog.dropTempView("people")
 |
 |      .. versionadded:: 2.0
 |
 |  createTempView(self, name)
 |      Creates a temporary view with this DataFrame.
 |
 |      The lifetime of this temporary table is tied to the :class:`SparkSession`
 |      that was used to create this :class:`DataFrame`.
 |      throws :class:`TempTableAlreadyExistsException`, if the view name already exists in the
 |      catalog.
 |
 |      >>> df.createTempView("people")
 |      >>> df2 = spark.sql("select * from people")
 |      >>> sorted(df.collect()) == sorted(df2.collect())
 |      True
 |      >>> df.createTempView("people")  # doctest: +IGNORE_EXCEPTION_DETAIL
 |      Traceback (most recent call last):
 |      ...
 |      AnalysisException: u"Temporary table 'people' already exists;"
 |      >>> spark.catalog.dropTempView("people")
 |
 |      .. versionadded:: 2.0
 |
 |  crosstab(self, col1, col2)
 |      Computes a pair-wise frequency table of the given columns. Also known as a contingency
 |      table. The number of distinct values for each column should be less than 1e4. At most 1e6
 |      non-zero pair frequencies will be returned.
 |      The first column of each row will be the distinct values of `col1` and the column names
 |      will be the distinct values of `col2`. The name of the first column will be `$col1_$col2`.
 |      Pairs that have no occurrences will have zero as their counts.
 |      :func:`DataFrame.crosstab` and :func:`DataFrameStatFunctions.crosstab` are aliases.
 |
 |      :param col1: The name of the first column. Distinct items will make the first item of
 |          each row.
 |      :param col2: The name of the second column. Distinct items will make the column names
 |          of the DataFrame.
 |
 |      .. versionadded:: 1.4
 |
 |  cube(self, *cols)
 |      Create a multi-dimensional cube for the current :class:`DataFrame` using
 |      the specified columns, so we can run aggregation on them.
 |
 |      >>> df.cube("name", df.age).count().orderBy("name", "age").show()
 |      +-----+----+-----+
 |      | name| age|count|
 |      +-----+----+-----+
 |      | null|null|    2|
 |      | null|   2|    1|
 |      | null|   5|    1|
 |      |Alice|null|    1|
 |      |Alice|   2|    1|
 |      |  Bob|null|    1|
 |      |  Bob|   5|    1|
 |      +-----+----+-----+
 |
 |      .. versionadded:: 1.4
 |
 |  describe(self, *cols)
 |      Computes statistics for numeric columns.
 |
 |      This include count, mean, stddev, min, and max. If no columns are
 |      given, this function computes statistics for all numerical columns.
 |
 |      .. note:: This function is meant for exploratory data analysis, as we make no         guarantee about the backward compatibility of the schema of the resulting DataFrame.
 |
 |      >>> df.describe().show()
 |      +-------+------------------+
 |      |summary|               age|
 |      +-------+------------------+
 |      |  count|                 2|
 |      |   mean|               3.5|
 |      | stddev|2.1213203435596424|
 |      |    min|                 2|
 |      |    max|                 5|
 |      +-------+------------------+
 |      >>> df.describe(['age', 'name']).show()
 |      +-------+------------------+-----+
 |      |summary|               age| name|
 |      +-------+------------------+-----+
 |      |  count|                 2|    2|
 |      |   mean|               3.5| null|
 |      | stddev|2.1213203435596424| null|
 |      |    min|                 2|Alice|
 |      |    max|                 5|  Bob|
 |      +-------+------------------+-----+
 |
 |      .. versionadded:: 1.3.1
 |
 |  distinct(self)
 |      Returns a new :class:`DataFrame` containing the distinct rows in this :class:`DataFrame`.
 |
 |      >>> df.distinct().count()
 |      2
 |
 |      .. versionadded:: 1.3
 |
 |  drop(self, col)
 |      Returns a new :class:`DataFrame` that drops the specified column.
 |      This is a no-op if schema doesn't contain the given column name(s).
 |
 |      :param col: a string name of the column to drop, or a
 |          :class:`Column` to drop.
 |
 |      >>> df.drop('age').collect()
 |      [Row(name=u'Alice'), Row(name=u'Bob')]
 |
 |      >>> df.drop(df.age).collect()
 |      [Row(name=u'Alice'), Row(name=u'Bob')]
 |
 |      >>> df.join(df2, df.name == df2.name, 'inner').drop(df.name).collect()
 |      [Row(age=5, height=85, name=u'Bob')]
 |
 |      >>> df.join(df2, df.name == df2.name, 'inner').drop(df2.name).collect()
 |      [Row(age=5, name=u'Bob', height=85)]
 |
 |      .. versionadded:: 1.4
 |
 |  dropDuplicates(self, subset=None)
 |      Return a new :class:`DataFrame` with duplicate rows removed,
 |      optionally only considering certain columns.
 |
 |      :func:`drop_duplicates` is an alias for :func:`dropDuplicates`.
 |
 |      >>> from pyspark.sql import Row
 |      >>> df = sc.parallelize([ \
 |      ...     Row(name='Alice', age=5, height=80), \
 |      ...     Row(name='Alice', age=5, height=80), \
 |      ...     Row(name='Alice', age=10, height=80)]).toDF()
 |      >>> df.dropDuplicates().show()
 |      +---+------+-----+
 |      |age|height| name|
 |      +---+------+-----+
 |      |  5|    80|Alice|
 |      | 10|    80|Alice|
 |      +---+------+-----+
 |
 |      >>> df.dropDuplicates(['name', 'height']).show()
 |      +---+------+-----+
 |      |age|height| name|
 |      +---+------+-----+
 |      |  5|    80|Alice|
 |      +---+------+-----+
 |
 |      .. versionadded:: 1.4
 |
 |  drop_duplicates = dropDuplicates(self, subset=None)
 |      :func:`drop_duplicates` is an alias for :func:`dropDuplicates`.
 |
 |      .. versionadded:: 1.4
 |
 |  dropna(self, how='any', thresh=None, subset=None)
 |      Returns a new :class:`DataFrame` omitting rows with null values.
 |      :func:`DataFrame.dropna` and :func:`DataFrameNaFunctions.drop` are aliases of each other.
 |
 |      :param how: 'any' or 'all'.
 |          If 'any', drop a row if it contains any nulls.
 |          If 'all', drop a row only if all its values are null.
 |      :param thresh: int, default None
 |          If specified, drop rows that have less than `thresh` non-null values.
 |          This overwrites the `how` parameter.
 |      :param subset: optional list of column names to consider.
 |
 |      >>> df4.na.drop().show()
 |      +---+------+-----+
 |      |age|height| name|
 |      +---+------+-----+
 |      | 10|    80|Alice|
 |      +---+------+-----+
 |
 |      .. versionadded:: 1.3.1
 |
 |  explain(self, extended=False)
 |      Prints the (logical and physical) plans to the console for debugging purpose.
 |
 |      :param extended: boolean, default ``False``. If ``False``, prints only the physical plan.
 |
 |      >>> df.explain()
 |      == Physical Plan ==
 |      Scan ExistingRDD[age#0,name#1]
 |
 |      >>> df.explain(True)
 |      == Parsed Logical Plan ==
 |      ...
 |      == Analyzed Logical Plan ==
 |      ...
 |      == Optimized Logical Plan ==
 |      ...
 |      == Physical Plan ==
 |      ...
 |
 |      .. versionadded:: 1.3
 |
 |  fillna(self, value, subset=None)
 |      Replace null values, alias for ``na.fill()``.
 |      :func:`DataFrame.fillna` and :func:`DataFrameNaFunctions.fill` are aliases of each other.
 |
 |      :param value: int, long, float, string, or dict.
 |          Value to replace null values with.
 |          If the value is a dict, then `subset` is ignored and `value` must be a mapping
 |          from column name (string) to replacement value. The replacement value must be
 |          an int, long, float, or string.
 |      :param subset: optional list of column names to consider.
 |          Columns specified in subset that do not have matching data type are ignored.
 |          For example, if `value` is a string, and subset contains a non-string column,
 |          then the non-string column is simply ignored.
 |
 |      >>> df4.na.fill(50).show()
 |      +---+------+-----+
 |      |age|height| name|
 |      +---+------+-----+
 |      | 10|    80|Alice|
 |      |  5|    50|  Bob|
 |      | 50|    50|  Tom|
 |      | 50|    50| null|
 |      +---+------+-----+
 |
 |      >>> df4.na.fill({'age': 50, 'name': 'unknown'}).show()
 |      +---+------+-------+
 |      |age|height|   name|
 |      +---+------+-------+
 |      | 10|    80|  Alice|
 |      |  5|  null|    Bob|
 |      | 50|  null|    Tom|
 |      | 50|  null|unknown|
 |      +---+------+-------+
 |
 |      .. versionadded:: 1.3.1
 |
 |  filter(self, condition)
 |      Filters rows using the given condition.
 |
 |      :func:`where` is an alias for :func:`filter`.
 |
 |      :param condition: a :class:`Column` of :class:`types.BooleanType`
 |          or a string of SQL expression.
 |
 |      >>> df.filter(df.age > 3).collect()
 |      [Row(age=5, name=u'Bob')]
 |      >>> df.where(df.age == 2).collect()
 |      [Row(age=2, name=u'Alice')]
 |
 |      >>> df.filter("age > 3").collect()
 |      [Row(age=5, name=u'Bob')]
 |      >>> df.where("age = 2").collect()
 |      [Row(age=2, name=u'Alice')]
 |
 |      .. versionadded:: 1.3
 |
 |  first(self)
 |      Returns the first row as a :class:`Row`.
 |
 |      >>> df.first()
 |      Row(age=2, name=u'Alice')
 |
 |      .. versionadded:: 1.3
 |
 |  foreach(self, f)
 |      Applies the ``f`` function to all :class:`Row` of this :class:`DataFrame`.
 |
 |      This is a shorthand for ``df.rdd.foreach()``.
 |
 |      >>> def f(person):
 |      ...     print(person.name)
 |      >>> df.foreach(f)
 |
 |      .. versionadded:: 1.3
 |
 |  foreachPartition(self, f)
 |      Applies the ``f`` function to each partition of this :class:`DataFrame`.
 |
 |      This a shorthand for ``df.rdd.foreachPartition()``.
 |
 |      >>> def f(people):
 |      ...     for person in people:
 |      ...         print(person.name)
 |      >>> df.foreachPartition(f)
 |
 |      .. versionadded:: 1.3
 |
 |  freqItems(self, cols, support=None)
 |      Finding frequent items for columns, possibly with false positives. Using the
 |      frequent element count algorithm described in
 |      "http://dx.doi.org/10.1145/762471.762473, proposed by Karp, Schenker, and Papadimitriou".
 |      :func:`DataFrame.freqItems` and :func:`DataFrameStatFunctions.freqItems` are aliases.
 |
 |      .. note::  This function is meant for exploratory data analysis, as we make no         guarantee about the backward compatibility of the schema of the resulting DataFrame.
 |
 |      :param cols: Names of the columns to calculate frequent items for as a list or tuple of
 |          strings.
 |      :param support: The frequency with which to consider an item 'frequent'. Default is 1%.
 |          The support must be greater than 1e-4.
 |
 |      .. versionadded:: 1.4
 |
 |  groupBy(self, *cols)
 |      Groups the :class:`DataFrame` using the specified columns,
 |      so we can run aggregation on them. See :class:`GroupedData`
 |      for all the available aggregate functions.
 |
 |      :func:`groupby` is an alias for :func:`groupBy`.
 |
 |      :param cols: list of columns to group by.
 |          Each element should be a column name (string) or an expression (:class:`Column`).
 |
 |      >>> df.groupBy().avg().collect()
 |      [Row(avg(age)=3.5)]
 |      >>> sorted(df.groupBy('name').agg({'age': 'mean'}).collect())
 |      [Row(name=u'Alice', avg(age)=2.0), Row(name=u'Bob', avg(age)=5.0)]
 |      >>> sorted(df.groupBy(df.name).avg().collect())
 |      [Row(name=u'Alice', avg(age)=2.0), Row(name=u'Bob', avg(age)=5.0)]
 |      >>> sorted(df.groupBy(['name', df.age]).count().collect())
 |      [Row(name=u'Alice', age=2, count=1), Row(name=u'Bob', age=5, count=1)]
 |
 |      .. versionadded:: 1.3
 |
 |  groupby = groupBy(self, *cols)
 |      :func:`groupby` is an alias for :func:`groupBy`.
 |
 |      .. versionadded:: 1.4
 |
 |  head(self, n=None)
 |      Returns the first ``n`` rows.
 |
 |      Note that this method should only be used if the resulting array is expected
 |      to be small, as all the data is loaded into the driver's memory.
 |
 |      :param n: int, default 1. Number of rows to return.
 |      :return: If n is greater than 1, return a list of :class:`Row`.
 |          If n is 1, return a single Row.
 |
 |      >>> df.head()
 |      Row(age=2, name=u'Alice')
 |      >>> df.head(1)
 |      [Row(age=2, name=u'Alice')]
 |
 |      .. versionadded:: 1.3
 |
 |  intersect(self, other)
 |      Return a new :class:`DataFrame` containing rows only in
 |      both this frame and another frame.
 |
 |      This is equivalent to `INTERSECT` in SQL.
 |
 |      .. versionadded:: 1.3
 |
 |  isLocal(self)
 |      Returns ``True`` if the :func:`collect` and :func:`take` methods can be run locally
 |      (without any Spark executors).
 |
 |      .. versionadded:: 1.3
 |
 |  join(self, other, on=None, how=None)
 |      Joins with another :class:`DataFrame`, using the given join expression.
 |
 |      :param other: Right side of the join
 |      :param on: a string for the join column name, a list of column names,
 |          a join expression (Column), or a list of Columns.
 |          If `on` is a string or a list of strings indicating the name of the join column(s),
 |          the column(s) must exist on both sides, and this performs an equi-join.
 |      :param how: str, default 'inner'.
 |          One of `inner`, `outer`, `left_outer`, `right_outer`, `leftsemi`.
 |
 |      The following performs a full outer join between ``df1`` and ``df2``.
 |

DataFrame[last_name: string, first_name: string, ssn: string, occupation: string, age: bigint]

How many partitions will the DataFrame be split into?

In [19]:
dataDF.rdd.getNumPartitions()

4

#### A note about DataFrames and queries
When you use DataFrames or Spark SQL, you are building up a _query plan_. Each transformation you apply to a DataFrame adds some information to the query plan. When you finally call an action, which triggers execution of your Spark job, several things happen:

1. Spark's Catalyst optimizer analyzes the query plan (called an _unoptimized logical query plan_) and attempts to optimize it. Optimizations include (but aren't limited to) rearranging and combining `filter()` operations for efficiency, converting Decimal operations to more efficient long integer operations, and pushing some operations down into the data source (e.g., a `filter()` operation might be translated to a SQL `WHERE` clause, if the data source is a traditional SQL RDBMS). The result of this optimization phase is an _optimized logical plan_.
2. Once Catalyst has an optimized logical plan, it then constructs multiple physical plans from it. Specifically, it implements the query in terms of lower level Spark RDD operations.
3. Catalyst chooses which physical plan to use via cost optimization. That is, it determines which physical plan is the most efficient (or least expensive), and uses that one.
4. Finally, once the physical RDD execution plan is established, Spark actually executes the job.

You can examine the query plan using the `explain()` function on a DataFrame. By default, `explain()` only shows you the final physical plan; however, if you pass it an argument of `True`, it will show you all phases.

(If you want to take a deeper dive into how Catalyst optimizes DataFrame queries, this blog post, while a little old, is an excellent overview: [Deep Dive into Spark SQL's Catalyst Optimizer](https://databricks.com/blog/2015/04/13/deep-dive-into-spark-sqls-catalyst-optimizer.html).)

Let's add a couple transformations to our DataFrame and look at the query plan on the resulting transformed DataFrame. Don't be too concerned if it looks like gibberish. As you gain more experience with Apache Spark, you'll begin to be able to use explain() to help you understand more about your DataFrame operations.

In [20]:
# Check operations about DataFrame
newDF = dataDF.distinct().select('*')
newDF.explain(True)

== Parsed Logical Plan ==
'Project [*]
+- Aggregate [last_name#0, first_name#1, ssn#2, occupation#3, age#4L], [last_name#0, first_name#1, ssn#2, occupation#3, age#4L]
   +- LogicalRDD [last_name#0, first_name#1, ssn#2, occupation#3, age#4L]

== Analyzed Logical Plan ==
last_name: string, first_name: string, ssn: string, occupation: string, age: bigint
Project [last_name#0, first_name#1, ssn#2, occupation#3, age#4L]
+- Aggregate [last_name#0, first_name#1, ssn#2, occupation#3, age#4L], [last_name#0, first_name#1, ssn#2, occupation#3, age#4L]
   +- LogicalRDD [last_name#0, first_name#1, ssn#2, occupation#3, age#4L]

== Optimized Logical Plan ==
Aggregate [last_name#0, first_name#1, ssn#2, occupation#3, age#4L], [last_name#0, first_name#1, ssn#2, occupation#3, age#4L]
+- LogicalRDD [last_name#0, first_name#1, ssn#2, occupation#3, age#4L]

== Physical Plan ==
*HashAggregate(keys=[last_name#0, first_name#1, ssn#2, occupation#3, age#4L], functions=[], output=[last_name#0, first_name#1, ssn#2, occupation#3, age#4L])
+- Exchange hashpartitioning(last_name#0, first_name#1, ssn#2, occupation#3, age#4L, 200)
   +- *HashAggregate(keys=[last_name#0, first_name#1, ssn#2, occupation#3, age#4L], functions=[], output=[last_name#0, first_name#1, ssn#2, occupation#3, age#4L])
      +- Scan ExistingRDD[last_name#0,first_name#1,ssn#2,occupation#3,age#4L]

In [21]:
newDF.show()

+---------+----------+-----------+--------------------+---+
|last_name|first_name|        ssn|          occupation|age|
+---------+----------+-----------+--------------------+---+
|     Ford|    Joshua|623-03-3910|   Drilling engineer| 30|
|   Horton|   Natalie|010-66-0981|Special effects a...|  5|
|  Andrade|       Amy|829-25-7984|Development worke...| 38|
|     Gray|  Brittany|121-10-1987|Geophysicist/fiel...| 10|
| Hamilton|  Michelle|462-75-7918|Corporate investm...| 18|
|     Nash|    Monica|111-45-5641|    Graphic designer| 25|
| Williams|      Dave|414-53-7365|   Drilling engineer| 46|
|   Horton|      Paul|554-51-8587|          Orthoptist|  6|
|   Howell|     Allen|505-67-4145|  Jewellery designer| 14|
|    Weber|    Steven|203-61-3012|          Counsellor|  7|
|    Walsh|     Lance|476-19-9916|       Buyer, retail| 24|
|   Harris|     David|574-84-8948|      Prison officer| 27|
|    Brown|     Jacob|497-76-1399|Administrator, Ci...| 31|
|  Perkins|   Michael|808-06-1434|           Press sub| 16|
|   Torres|      Paul|591-77-3082|        Statistician| 35|
| Crawford|     Shawn|414-88-5121|Operational inves...| 38|
|  Johnson|      Leah|643-83-4528|Teacher, English ...| 16|
| Reynolds|   Stephen|617-93-3629|Chartered accountant| 45|
|   Carter|   Jessica|060-92-0860|      Pharmacologist| 27|
|  Walters|     Nancy|843-15-5515|          Aid worker| 16|
+---------+----------+-----------+--------------------+---+
only showing top 20 rows

### (3c) Subtract one from each value using `select`
So far, we've created a distributed DataFrame that is split into many partitions, where each partition is stored on a single machine in our cluster. Let's look at what happens when we do a basic operation on the dataset. Many useful data analysis operations can be specified as "do something to each item in the dataset". These data-parallel operations are convenient because each item in the dataset can be processed individually: the operation on one entry doesn't effect the operations on any of the other entries. Therefore, Spark can parallelize the operation.

One of the most common DataFrame operations is `select()`, and it works more or less like a SQL `SELECT` statement: You can select specific columns from the DataFrame, and you can even use `select()` to create new columns with values that are derived from existing column values. We can use `select()` to create a new column that decrements the value of the existing `age` column.

`select()` is a transformation. It returns a new DataFrame that captures both the previous DataFrame and the operation to add to the query (`select`, in this case). But it does not actually execute anything on the cluster. When transforming DataFrames, we are building up a _query plan_. That query plan will be optimized, implemented (in terms of RDDs), and executed by Spark _only_ when we call an action.

In [23]:
# Transform dataDF through a select transformation and rename the newly created '(age -1)' column to 'age'
# Because select is a transformation and Spark uses lazy evaluation, no jobs, stages,
# or tasks will be launched when we run this code.
subDF = dataDF.select('last_name', 'first_name', 'ssn', 'occupation', (dataDF.age - 1).alias('age'))

In [24]:
subDF.explain(True)

== Parsed Logical Plan ==
'Project [unresolvedalias('last_name, None), unresolvedalias('first_name, None), unresolvedalias('ssn, None), unresolvedalias('occupation, None), (age#4L - 1) AS age#39]
+- LogicalRDD [last_name#0, first_name#1, ssn#2, occupation#3, age#4L]

== Analyzed Logical Plan ==
last_name: string, first_name: string, ssn: string, occupation: string, age: bigint
Project [last_name#0, first_name#1, ssn#2, occupation#3, (age#4L - cast(1 as bigint)) AS age#39L]
+- LogicalRDD [last_name#0, first_name#1, ssn#2, occupation#3, age#4L]

== Optimized Logical Plan ==
Project [last_name#0, first_name#1, ssn#2, occupation#3, (age#4L - 1) AS age#39L]
+- LogicalRDD [last_name#0, first_name#1, ssn#2, occupation#3, age#4L]

== Physical Plan ==
*Project [last_name#0, first_name#1, ssn#2, occupation#3, (age#4L - 1) AS age#39L]
+- Scan ExistingRDD[last_name#0,first_name#1,ssn#2,occupation#3,age#4L]

### (3d) Use `collect` to view results
To see a list of elements decremented by one, we need to create a new list on the driver from the the data distributed in the executor nodes. To do this we can call the `collect()` method on our DataFrame. `collect()` is often used after transformations to ensure that we are only returning a small amount of data to the driver. This is done because the data returned to the driver must fit into the driver's available memory. If not, the driver will crash.

The `collect()` method is the first action operation that we have encountered. Action operations cause Spark to perform the (lazy) transformation operations that are required to compute the values returned by the action. In our example, this means that tasks will now be launched to perform the createDataFrame, select, and collect operations.

In the diagram, the dataset is broken into four partitions, so four `collect()` tasks are launched. Each task collects the entries in its partition and sends the result to the driver, which creates a list of the values, as shown in the figure below.
Now let's run `collect()` on subDF.

<img src="http://spark-mooc.github.io/web-assets/images/cs105x/diagram-3d.png" style="height:700px;float:right"/>

In [25]:
# Let's collect the data
results = subDF.collect()
print results

[Row(last_name=u'Stein', first_name=u'Jacob', ssn=u'039-19-0531', occupation=u'Education officer, community', age=19), Row(last_name=u'Hamilton', first_name=u'Tommy', ssn=u'824-45-1140', occupation=u'Chief Operating Officer', age=36), Row(last_name=u'Chapman', first_name=u'Deborah', ssn=u'735-56-4346', occupation=u'Copywriter, advertising', age=19), Row(last_name=u'Moody', first_name=u'David', ssn=u'382-11-7793', occupation=u'Designer, multimedia', age=38), Row(last_name=u'Oconnor', first_name=u'Michael', ssn=u'356-45-3733', occupation=u'Paediatric nurse', age=27), Row(last_name=u'Dudley', first_name=u'Steven', ssn=u'087-09-9992', occupation=u'Nurse, adult', age=45), Row(last_name=u'Rice', first_name=u'Derek', ssn=u'048-55-3413', occupation=u'Brewing technologist', age=38), Row(last_name=u'Pratt', first_name=u'Kimberly', ssn=u'076-83-7404', occupation=u'Sports coach', age=9), Row(last_name=u'Norton', first_name=u'Ryan', ssn=u'504-17-8123', occupation=u'Surveyor, mining', age=34), Row(last_name=u'Taylor', first_name=u'Cynthia', ssn=u'436-83-3006', occupation=u'Osteopath', age=16), Row(last_name=u'Nguyen', first_name=u'Gary', ssn=u'194-03-8285', occupation=u'Forensic scientist', age=35), Row(last_name=u'Williams', first_name=u'Barbara', ssn=u'206-33-1107', occupation=u'Insurance risk surveyor', age=28), Row(last_name=u'Shaffer', first_name=u'Danny', ssn=u'554-12-0804', occupation=u'Bookseller', age=44), Row(last_name=u'Evans', first_name=u'Nicholas', ssn=u'711-43-1509', occupation=u'Press photographer', age=3), Row(last_name=u'Miller', first_name=u'Tanya', ssn=u'867-83-8955', occupation=u'Pharmacologist', age=2), Row(last_name=u'Jones', first_name=u'Robin', ssn=u'796-17-7156', occupation=u'Engineer, building services', age=13), Row(last_name=u'Holland', first_name=u'Hannah', ssn=u'249-01-5612', occupation=u'Public house manager', age=30), Row(last_name=u'Patterson', first_name=u'Bobby', ssn=u'056-60-8511', occupation=u'Statistician', age=36), Row(last_name=u'Powell', first_name=u'Tammy', ssn=u'850-80-0231', occupation=u'Careers adviser', age=17), Row(last_name=u'Patterson', first_name=u'Andrew', ssn=u'354-55-4587', occupation=u'Radio broadcast assistant', age=39), Row(last_name=u'Cardenas', first_name=u'Joseph', ssn=u'399-09-2680', occupation=u'Senior tax professional/tax inspector', age=14), Row(last_name=u'Johns', first_name=u'Michelle', ssn=u'023-90-7449', occupation=u'Health service manager', age=45), Row(last_name=u'Mcdowell', first_name=u'Jennifer', ssn=u'216-65-9487', occupation=u'Education officer, museum', age=23), Row(last_name=u'Deleon', first_name=u'Amanda', ssn=u'852-49-6969', occupation=u'Chief Operating Officer', age=7), Row(last_name=u'Anderson', first_name=u'Philip', ssn=u'551-46-6107', occupation=u'Planning and development surveyor', age=11), Row(last_name=u'Mejia', first_name=u'Anna', ssn=u'837-45-1924', occupation=u'Designer, television/film set', age=24), Row(last_name=u'White', first_name=u'Rebecca', ssn=u'121-52-8368', occupation=u'Buyer, industrial', age=17), Row(last_name=u'Shaw', first_name=u'David', ssn=u'672-57-1650', occupation=u'Production manager', age=23), Row(last_name=u'Paul', first_name=u'Victoria', ssn=u'370-63-8920', occupation=u'Environmental manager', age=22), Row(last_name=u'Hays', first_name=u'Jeff', ssn=u'661-20-4642', occupation=u'Music tutor', age=22), Row(last_name=u'Nguyen', first_name=u'Erica', ssn=u'251-56-0999', occupation=u'Agricultural engineer', age=42), Row(last_name=u'Skinner', first_name=u'Christopher', ssn=u'621-23-3079', occupation=u'Operational investment banker', age=46), Row(last_name=u'Jackson', first_name=u'Nathan', ssn=u'682-09-3573', occupation=u'Administrator, sports', age=35), Row(last_name=u'Thompson', first_name=u'Terri', ssn=u'607-24-8694', occupation=u'Food technologist', age=33), Row(last_name=u'Figueroa', first_name=u'Ashley', ssn=u'439-10-9336', occupation=u'Games developer', age=20), Row(last_name=u'Lewis', first_name=u'David', ssn=u'695-60-0033', occupation=u'Field seismologist', age=9), Row(last_name=u'Rodgers', first_name=u'Beverly', ssn=u'819-57-7194', occupation=u'Records manager', age=0), Row(last_name=u'Randall', first_name=u'Dennis', ssn=u'077-40-8314', occupation=u'Lecturer, higher education', age=25), Row(last_name=u'Quinn', first_name=u'Teresa', ssn=u'823-43-5986', occupation=u'Horticulturist, amenity', age=35), Row(last_name=u'Ford', first_name=u'Joshua', ssn=u'623-03-3910', occupation=u'Drilling engineer', age=29), Row(last_name=u'Watts', first_name=u'Joseph', ssn=u'225-30-2177', occupation=u'Equality and diversity officer', age=25), Row(last_name=u'Martin', first_name=u'Willie', ssn=u'174-81-6535', occupation=u'Engineer, electrical', age=45), Row(last_name=u'Davis', first_name=u'Joseph', ssn=u'874-11-0910', occupation=u'Careers adviser', age=17), Row(last_name=u'Rodriguez', first_name=u'Ross', ssn=u'275-26-3828', occupation=u'Production assistant, television', age=39), Row(last_name=u'Rubio', first_name=u'Christopher', ssn=u'750-41-6999', occupation=u'Surveyor, planning and development', age=11), Row(last_name=u'Johnson', first_name=u'Amanda', ssn=u'494-58-8536', occupation=u'Higher education lecturer', age=4), Row(last_name=u'Haas', first_name=u'Emily', ssn=u'518-20-4587', occupation=u'Restaurant manager', age=40), Row(last_name=u'Young', first_name=u'Eddie', ssn=u'093-34-0390', occupation=u'Customer service manager', age=22), Row(last_name=u'Gordon', first_name=u'Shawn', ssn=u'422-63-3984', occupation=u'Aid worker', age=22), Row(last_name=u'Wilson', first_name=u'Tiffany', ssn=u'560-10-3377', occupation=u'Development worker, community', age=47), Row(last_name=u'Jenkins', first_name=u'Robert', ssn=u'828-24-7280', occupation=u'Data scientist', age=28), Row(last_name=u'Webb', first_name=u'Megan', ssn=u'664-41-7482', occupation=u'Counsellor', age=38), Row(last_name=u'Lewis', first_name=u'Jaime', ssn=u'340-54-3457', occupation=u'Learning disability nurse', age=37), Row(last_name=u'Ford', first_name=u'Kaitlyn', ssn=u'017-37-9292', occupation=u'Dancer', age=28), Row(last_name=u'Hall', first_name=u'Monique', ssn=u'518-71-6777', occupation=u'Research scientist (medical)', age=38), Row(last_name=u'Mendoza', first_name=u'Michael', ssn=u'227-93-1686', occupation=u'Sub', age=31), Row(last_name=u'Johnson', first_name=u'Nicholas', ssn=u'157-13-2050', occupation=u'IT consultant', age=0), Row(last_name=u'Ball', first_name=u'Jacqueline', ssn=u'604-21-5781', occupation=u'Clinical molecular geneticist', age=19), Row(last_name=u'Walker', first_name=u'Joseph', ssn=u'079-99-5775', occupation=u'Restaurant manager, fast food', age=29), Row(last_name=u'Hernandez', first_name=u'Richard', ssn=u'639-98-4417', occupation=u'Environmental health practitioner', age=28), Row(last_name=u'Munoz', first_name=u'Kayla', ssn=u'784-13-1014', occupation=u'English as a second language teacher', age=33), Row(last_name=u'Fry', first_name=u'Jeffrey', ssn=u'337-29-9383', occupation=u'Careers adviser', age=36), Row(last_name=u'Preston', first_name=u'Tyler', ssn=u'885-52-6902', occupation=u'Product/process development scientist', age=36), Row(last_name=u'Murphy', first_name=u'Lisa', ssn=u'475-39-0779', occupation=u'Radio broadcast assistant', age=46), Row(last_name=u'Johnson', first_name=u'Candice', ssn=u'639-80-6841', occupation=u'Electrical engineer', age=6), Row(last_name=u'Neal', first_name=u'Amanda', ssn=u'685-37-7370', occupation=u'Tourism officer', age=39), Row(last_name=u'Kaufman', first_name=u'Michael', ssn=u'258-69-6049', occupation=u'Chemist, analytical', age=24), Row(last_name=u'Smith', first_name=u'Ashlee', ssn=u'387-51-5783', occupation=u'Teacher, music', age=17), Row(last_name=u'Arias', first_name=u'Mark', ssn=u'501-67-7559', occupation=u'Management consultant', age=4), Row(last_name=u'Webster', first_name=u'Jennifer', ssn=u'156-76-6778', occupation=u'English as a second language teacher', age=34), Row(last_name=u'Rose', first_name=u'Henry', ssn=u'314-03-4053', occupation=u'Broadcast engineer', age=26), Row(last_name=u'Barry', first_name=u'Jeremy', ssn=u'004-41-3243', occupation=u'Accommodation manager', age=15), Row(last_name=u'Jones', first_name=u'Jeremy', ssn=u'648-72-8898', occupation=u'Product manager', age=8), Row(last_name=u'David', first_name=u'Tracy', ssn=u'384-34-4827', occupation=u'Lawyer', age=38), Row(last_name=u'Ibarra', first_name=u'Anthony', ssn=u'843-46-1528', occupation=u'Dealer', age=15), Row(last_name=u'Larson', first_name=u'Joseph', ssn=u'076-36-8031', occupation=u'Embryologist, clinical', age=27), Row(last_name=u'Turner', first_name=u'Ariana', ssn=u'176-16-1892', occupation=u'Lecturer, further education', age=39), Row(last_name=u'Delgado', first_name=u'Sonia', ssn=u'283-58-4951', occupation=u'Solicitor', age=7), Row(last_name=u'Bishop', first_name=u'Jonathan', ssn=u'714-87-5335', occupation=u'Medical physicist', age=11), Row(last_name=u'Pineda', first_name=u'Connor', ssn=u'041-63-6459', occupation=u'Dentist', age=11), Row(last_name=u'Craig', first_name=u'Jacob', ssn=u'656-19-9875', occupation=u'Conference centre manager', age=28), Row(last_name=u'Robinson', first_name=u'Adam', ssn=u'279-56-1630', occupation=u'Financial manager', age=1), Row(last_name=u'Holloway', first_name=u'Julia', ssn=u'115-33-9587', occupation=u'Animator', age=3), Row(last_name=u'Fleming', first_name=u'Jodi', ssn=u'833-40-8181', occupation=u'Agricultural engineer', age=0), Row(last_name=u'Powell', first_name=u'Kimberly', ssn=u'102-37-5719', occupation=u'Contracting civil engineer', age=6), Row(last_name=u'Gamble', first_name=u'Julie', ssn=u'374-87-4372', occupation=u'Editor, film/video', age=17), Row(last_name=u'Brennan', first_name=u'Christopher', ssn=u'831-32-0206', occupation=u'Scientist, research (physical sciences)', age=44), Row(last_name=u'Green', first_name=u'Karen', ssn=u'531-17-1551', occupation=u'Operational investment banker', age=23), Row(last_name=u'Cook', first_name=u'Jessica', ssn=u'811-23-6545', occupation=u'Town planner', age=24), Row(last_name=u'Walker', first_name=u'Rhonda', ssn=u'648-03-3938', occupation=u'Scientist, clinical (histocompatibility and immunogenetics)', age=23), Row(last_name=u'Perez', first_name=u'Elizabeth', ssn=u'571-87-0459', occupation=u'Sports coach', age=43), Row(last_name=u'Valencia', first_name=u'Alicia', ssn=u'274-89-5763', occupation=u'Lecturer, further education', age=6), Row(last_name=u'Williams', first_name=u'Brandon', ssn=u'590-16-3719', occupation=u'Doctor, general practice', age=17), Row(last_name=u'Hunt', first_name=u'Michael', ssn=u'745-13-3849', occupation=u'Rural practice surveyor', age=25), Row(last_name=u'Sandoval', first_name=u'Catherine', ssn=u'295-44-6367', occupation=u'Lawyer', age=47), Row(last_name=u'Stephenson', first_name=u'Ronald', ssn=u'659-93-6622', occupation=u'Art gallery manager', age=33), Row(last_name=u'Barton', first_name=u'Ryan', ssn=u'728-17-7313', occupation=u'Art therapist', age=26), Row(last_name=u'Smith', first_name=u'Rachel', ssn=u'708-44-5175', occupation=u'Surveyor, building control', age=39), Row(last_name=u'Griffith', first_name=u'Valerie', ssn=u'182-03-1388', occupation=u'Exhibition designer', age=6), Row(last_name=u'Jordan', first_name=u'Ashley', ssn=u'399-94-7975', occupation=u'Editor, film/video', age=32), Row(last_name=u'Price', first_name=u'Ronald', ssn=u'694-58-1212', occupation=u'Runner, broadcasting/film/video', age=25), Row(last_name=u'Esparza', first_name=u'John', ssn=u'607-25-0733', occupation=u'Therapeutic radiographer', age=30), Row(last_name=u'Peck', first_name=u'Douglas', ssn=u'133-19-9920', occupation=u'Secretary, company', age=2), Row(last_name=u'Black', first_name=u'Kimberly', ssn=u'677-92-2450', occupation=u'Chemical engineer', age=14), Row(last_name=u'Charles', first_name=u'Mr.', ssn=u'323-86-6963', occupation=u'Engineer, civil (consulting)', age=19), Row(last_name=u'Moore', first_name=u'David', ssn=u'133-48-6552', occupation=u'Surveyor, hydrographic', age=37), Row(last_name=u'Ramirez', first_name=u'Christine', ssn=u'087-21-9165', occupation=u'Scientist, water quality', age=25), Row(last_name=u'Morrow', first_name=u'Alex', ssn=u'533-54-4033', occupation=u'Town planner', age=3), Row(last_name=u'Johnson', first_name=u'Christian', ssn=u'860-63-4089', occupation=u'Medical physicist', age=17), Row(last_name=u'Blair', first_name=u'Steven', ssn=u'675-95-9698', occupation=u'Pathologist', age=34), Row(last_name=u'Jones', first_name=u'Natalie', ssn=u'429-52-5642', occupation=u'Research scientist (medical)', age=21), Row(last_name=u'Cummings', first_name=u'Jeanette', ssn=u'149-57-3736', occupation=u'Broadcast journalist', age=16), Row(last_name=u'Payne', first_name=u'Jacob', ssn=u'246-27-8489', occupation=u'Fisheries officer', age=36), Row(last_name=u'Williams', first_name=u'Patrick', ssn=u'812-88-9795', occupation=u'Professor Emeritus', age=47), Row(last_name=u'Meyer', first_name=u'Cristian', ssn=u'602-45-1203', occupation=u'Gaffer', age=8), Row(last_name=u'Murphy', first_name=u'Michael', ssn=u'663-26-5493', occupation=u'Surveyor, mining', age=7), Row(last_name=u'Carlson', first_name=u'Jerry', ssn=u'823-88-1208', occupation=u'Arts administrator', age=21), Row(last_name=u'Schultz', first_name=u'Victoria', ssn=u'159-58-7310', occupation=u'Recycling officer', age=45), Row(last_name=u'Jackson', first_name=u'Cynthia', ssn=u'699-10-4819', occupation=u'Fitness centre manager', age=43), Row(last_name=u'Miller', first_name=u'Jacob', ssn=u'691-69-2880', occupation=u'Chief of Staff', age=29), Row(last_name=u'Wang', first_name=u'Edward', ssn=u'761-51-6731', occupation=u'Trading standards officer', age=15), Row(last_name=u'Smith', first_name=u'Christopher', ssn=u'409-86-2882', occupation=u'Engineering geologist', age=5), Row(last_name=u'Thomas', first_name=u'Breanna', ssn=u'700-90-3741', occupation=u'Clothing/textile technologist', age=45), Row(last_name=u'Roberts', first_name=u'Luis', ssn=u'562-33-8154', occupation=u'Psychologist, clinical', age=12), Row(last_name=u'Davis', first_name=u'Briana', ssn=u'687-12-3800', occupation=u'Research officer, political party', age=25), Row(last_name=u'Arias', first_name=u'Jessica', ssn=u'320-58-5487', occupation=u'Nurse, learning disability', age=46), Row(last_name=u'Johnson', first_name=u'Hector', ssn=u'753-83-1027', occupation=u'Surveyor, rural practice', age=17), Row(last_name=u'Gallegos', first_name=u'Michael', ssn=u'203-15-1520', occupation=u'Water engineer', age=0), Row(last_name=u'George', first_name=u'Kathryn', ssn=u'068-01-3503', occupation=u'Designer, graphic', age=35), Row(last_name=u'Moore', first_name=u'Scott', ssn=u'514-35-9041', occupation=u'Public house manager', age=25), Row(last_name=u'Frederick', first_name=u'Anthony', ssn=u'607-75-8076', occupation=u'Ceramics designer', age=28), Row(last_name=u'Evans', first_name=u'Raven', ssn=u'829-56-8556', occupation=u'Health physicist', age=9), Row(last_name=u'Washington', first_name=u'Gregory', ssn=u'325-60-0118', occupation=u'Advertising account planner', age=47), Row(last_name=u'Logan', first_name=u'Elizabeth', ssn=u'510-11-4273', occupation=u'Recruitment consultant', age=31), Row(last_name=u'King', first_name=u'Jacqueline', ssn=u'506-33-4081', occupation=u'Risk manager', age=2), Row(last_name=u'Cook', first_name=u'Ryan', ssn=u'460-83-5028', occupation=u'Bookseller', age=3), Row(last_name=u'Marsh', first_name=u'Destiny', ssn=u'560-35-4759', occupation=u'Hospital pharmacist', age=39), Row(last_name=u'Luna', first_name=u'Peter', ssn=u'186-20-8593', occupation=u'Scientist, audiological', age=21), Row(last_name=u'Rios', first_name=u'Jennifer', ssn=u'212-15-4199', occupation=u'Child psychotherapist', age=25), Row(last_name=u'Johnson', first_name=u'Holly', ssn=u'093-03-1883', occupation=u'Immunologist', age=1), Row(last_name=u'Barron', first_name=u'Courtney', ssn=u'519-80-0824', occupation=u'Engineer, broadcasting (operations)', age=11), Row(last_name=u'Schneider', first_name=u'Jessica', ssn=u'794-09-9597', occupation=u'Engineer, water', age=26), Row(last_name=u'Wright', first_name=u'Roger', ssn=u'287-49-5958', occupation=u'Editor, magazine features', age=13), Row(last_name=u'Watkins', first_name=u'Isaac', ssn=u'698-36-7612', occupation=u'Purchasing manager', age=16), Row(last_name=u'Gonzalez', first_name=u'Stephanie', ssn=u'880-98-8223', occupation=u'Teacher, primary school', age=39), Row(last_name=u'Hughes', first_name=u'Amy', ssn=u'255-17-3490', occupation=u'Chemical engineer', age=10), Row(last_name=u'Marshall', first_name=u'Geoffrey', ssn=u'826-82-5735', occupation=u'Designer, fashion/clothing', age=2), Row(last_name=u'Munoz', first_name=u'Denise', ssn=u'617-10-3267', occupation=u'Outdoor activities/education manager', age=32), Row(last_name=u'Rodriguez', first_name=u'Laura', ssn=u'380-71-1131', occupation=u'Field trials officer', age=7), Row(last_name=u'Nelson', first_name=u'William', ssn=u'618-59-7628', occupation=u'Sales promotion account executive', age=39), Row(last_name=u'Peterson', first_name=u'Katherine', ssn=u'119-45-7899', occupation=u'Designer, industrial/product', age=28), Row(last_name=u'Williams', first_name=u'Nicole', ssn=u'574-72-0358', occupation=u'Advice worker', age=4), Row(last_name=u'Hubbard', first_name=u'Travis', ssn=u'202-29-0251', occupation=u'Phytotherapist', age=13), Row(last_name=u'Williams', first_name=u'Jerry', ssn=u'062-08-0637', occupation=u'Engineer, water', age=32), Row(last_name=u'Hood', first_name=u'Haley', ssn=u'754-44-5517', occupation=u'Programmer, multimedia', age=19), Row(last_name=u'Dorsey', first_name=u'Brandon', ssn=u'862-30-8837', occupation=u'Embryologist, clinical', age=21), Row(last_name=u'Wallace', first_name=u'Kenneth', ssn=u'067-92-3736', occupation=u'Professor Emeritus', age=23), Row(last_name=u'Lynch', first_name=u'Zachary', ssn=u'622-55-9599', occupation=u'Dramatherapist', age=39), Row(last_name=u'Rodriguez', first_name=u'Donald', ssn=u'873-75-1255', occupation=u'Research scientist (physical sciences)', age=39), Row(last_name=u'Newman', first_name=u'Rebecca', ssn=u'050-93-5616', occupation=u'Barista', age=14), Row(last_name=u'Williams', first_name=u'Blake', ssn=u'248-73-1904', occupation=u'Scientist, clinical (histocompatibility and immunogenetics)', age=33), Row(last_name=u'Martin', first_name=u'Aaron', ssn=u'059-08-0977', occupation=u'Scientist, research (physical sciences)', age=18), Row(last_name=u'Johnson', first_name=u'Mikayla', ssn=u'746-47-0319', occupation=u'Wellsite geologist', age=37), Row(last_name=u'Bernard', first_name=u'Dawn', ssn=u'307-36-3457', occupation=u'Engineer, chemical', age=21), Row(last_name=u'Gomez', first_name=u'Erin', ssn=u'045-58-9521', occupation=u'Pension scheme manager', age=17), Row(last_name=u'Mack', first_name=u'Bradley', ssn=u'662-80-6804', occupation=u'Market researcher', age=4), Row(last_name=u'Howard', first_name=u'Nicholas', ssn=u'188-57-7205', occupation=u'Astronomer', age=8), Row(last_name=u'Ellis', first_name=u'George', ssn=u'193-08-3697', occupation=u'Surveyor, minerals', age=3), Row(last_name=u'Thornton', first_name=u'Heather', ssn=u'265-74-7056', occupation=u'Solicitor', age=33), Row(last_name=u'Adams', first_name=u'Bobby', ssn=u'869-88-6439', occupation=u'Scientist, research (life sciences)', age=44), Row(last_name=u'Young', first_name=u'Kristin', ssn=u'033-41-6170', occupation=u'Learning mentor', age=13), Row(last_name=u'Cross', first_name=u'David', ssn=u'856-53-4309', occupation=u'Educational psychologist', age=22), Row(last_name=u'Williams', first_name=u'Daniel', ssn=u'318-62-6385', occupation=u'Clinical research associate', age=39), Row(last_name=u'Quinn', first_name=u'Samuel', ssn=u'143-25-6466', occupation=u'Museum/gallery exhibitions officer', age=37), Row(last_name=u'Dawson', first_name=u'Kim', ssn=u'096-29-1552', occupation=u'Higher education careers adviser', age=40), Row(last_name=u'Horton', first_name=u'Dominic', ssn=u'057-78-9985', occupation=u'Food technologist', age=17), Row(last_name=u'Solis', first_name=u'Pamela', ssn=u'534-51-7738', occupation=u'Travel agency manager', age

A better way to visualize the data is to use the `show()` method. If you don't tell `show()` how many rows to display, it displays 20 rows.

In [26]:
subDF.show()

+---------+----------+-----------+--------------------+---+
|last_name|first_name|        ssn|          occupation|age|
+---------+----------+-----------+--------------------+---+
|    Stein|     Jacob|039-19-0531|Education officer...| 19|
| Hamilton|     Tommy|824-45-1140|Chief Operating O...| 36|
|  Chapman|   Deborah|735-56-4346|Copywriter, adver...| 19|
|    Moody|     David|382-11-7793|Designer, multimedia| 38|
|  Oconnor|   Michael|356-45-3733|    Paediatric nurse| 27|
|   Dudley|    Steven|087-09-9992|        Nurse, adult| 45|
|     Rice|     Derek|048-55-3413|Brewing technologist| 38|
|    Pratt|  Kimberly|076-83-7404|        Sports coach|  9|
|   Norton|      Ryan|504-17-8123|    Surveyor, mining| 34|
|   Taylor|   Cynthia|436-83-3006|           Osteopath| 16|
|   Nguyen|      Gary|194-03-8285|  Forensic scientist| 35|
| Williams|   Barbara|206-33-1107|Insurance risk su...| 28|
|  Shaffer|     Danny|554-12-0804|          Bookseller| 44|
|    Evans|  Nicholas|711-43-1509|  Press photographer|  3|
|   Miller|     Tanya|867-83-8955|      Pharmacologist|  2|
|    Jones|     Robin|796-17-7156|Engineer, buildin...| 13|
|  Holland|    Hannah|249-01-5612|Public house manager| 30|
|Patterson|     Bobby|056-60-8511|        Statistician| 36|
|   Powell|     Tammy|850-80-0231|     Careers adviser| 17|
|Patterson|    Andrew|354-55-4587|Radio broadcast a...| 39|
+---------+----------+-----------+--------------------+---+
only showing top 20 rows

If you'd prefer that `show()` not truncate the data, you can tell it not to:

In [27]:
subDF.show(truncate=False)

+---------+----------+-----------+----------------------------+---+
|last_name|first_name|ssn        |occupation                  |age|
+---------+----------+-----------+----------------------------+---+
|Stein    |Jacob     |039-19-0531|Education officer, community|19 |
|Hamilton |Tommy     |824-45-1140|Chief Operating Officer     |36 |
|Chapman  |Deborah   |735-56-4346|Copywriter, advertising     |19 |
|Moody    |David     |382-11-7793|Designer, multimedia        |38 |
|Oconnor  |Michael   |356-45-3733|Paediatric nurse            |27 |
|Dudley   |Steven    |087-09-9992|Nurse, adult                |45 |
|Rice     |Derek     |048-55-3413|Brewing technologist        |38 |
|Pratt    |Kimberly  |076-83-7404|Sports coach                |9  |
|Norton   |Ryan      |504-17-8123|Surveyor, mining            |34 |
|Taylor   |Cynthia   |436-83-3006|Osteopath                   |16 |
|Nguyen   |Gary      |194-03-8285|Forensic scientist          |35 |
|Williams |Barbara   |206-33-1107|Insurance risk surveyor     |28 |
|Shaffer  |Danny     |554-12-0804|Bookseller                  |44 |
|Evans    |Nicholas  |711-43-1509|Press photographer          |3  |
|Miller   |Tanya     |867-83-8955|Pharmacologist              |2  |
|Jones    |Robin     |796-17-7156|Engineer, building services |13 |
|Holland  |Hannah    |249-01-5612|Public house manager        |30 |
|Patterson|Bobby     |056-60-8511|Statistician                |36 |
|Powell   |Tammy     |850-80-0231|Careers adviser             |17 |
|Patterson|Andrew    |354-55-4587|Radio broadcast assistant   |39 |
+---------+----------+-----------+----------------------------+---+
only showing top 20 rows

### (3e) Use `count` to get total
One of the most basic jobs that we can run is the `count()` job which will count the number of elements in a DataFrame, using the `count()` action. Since `select()` creates a new DataFrame with the same number of elements as the starting DataFrame, we expect that applying `count()` to each DataFrame will return the same result.

Note that because `count()` is an action operation, if we had not already performed an action with `collect()`, then Spark would now perform the transformation operations when we executed `count()`.

Each task counts the entries in its partition and sends the result to your SparkContext, which adds up all of the counts. The figure on the right shows what would happen if we ran `count()` on a small example dataset with just four partitions.

<img src="http://spark-mooc.github.io/web-assets/images/cs105x/diagram-3e.png" style="height:700px;float:right"/>

In [28]:
print(dataDF.count())
print(subDF.count())

10000
10000

### (3f) Apply transformation `filter` and view results with `collect`
Next, we'll create a new DataFrame that only contains the people whose ages are less than 10. To do this, we'll use the `filter()` transformation. (You can also use `where()`, an alias for `filter()`, if you prefer something more SQL-like). The `filter()` method is a transformation operation that creates a new DataFrame from the input DataFrame, keeping only values that match the filter expression.

The figure shows how this might work on the small four-partition dataset.

To view the filtered list of elements less than 10, we need to create a new list on the driver from the distributed data on the executor nodes. We use the `collect()` method to return a list that contains all of the elements in this filtered DataFrame to the driver program.

<img src="http://spark-mooc.github.io/web-assets/images/cs105x/diagram-3f.png" style="height:700px;float:right"/>

In [30]:
from pyspark.sql.types import IntegerType
subDF.age.cast(IntegerType())
filteredDF = subDF.filter(subDF.age < 10)
filteredDF.show(truncate=False)
filteredDF.count()

+---------+----------+-----------+---------------------------+---+
|last_name|first_name|ssn        |occupation                 |age|
+---------+----------+-----------+---------------------------+---+
|Pratt    |Kimberly  |076-83-7404|Sports coach               |9  |
|Evans    |Nicholas  |711-43-1509|Press photographer         |3  |
|Miller   |Tanya     |867-83-8955|Pharmacologist             |2  |
|Deleon   |Amanda    |852-49-6969|Chief Operating Officer    |7  |
|Lewis    |David     |695-60-0033|Field seismologist         |9  |
|Rodgers  |Beverly   |819-57-7194|Records manager            |0  |
|Johnson  |Amanda    |494-58-8536|Higher education lecturer  |4  |
|Johnson  |Nicholas  |157-13-2050|IT consultant              |0  |
|Johnson  |Candice   |639-80-6841|Electrical engineer        |6  |
|Arias    |Mark      |501-67-7559|Management consultant      |4  |
|Jones    |Jeremy    |648-72-8898|Product manager            |8  |
|Delgado  |Sonia     |283-58-4951|Solicitor                  |7  |
|Robinson |Adam      |279-56-1630|Financial manager          |1  |
|Holloway |Julia     |115-33-9587|Animator                   |3  |
|Fleming  |Jodi      |833-40-8181|Agricultural engineer      |0  |
|Powell   |Kimberly  |102-37-5719|Contracting civil engineer |6  |
|Valencia |Alicia    |274-89-5763|Lecturer, further education|6  |
|Griffith |Valerie   |182-03-1388|Exhibition designer        |6  |
|Peck     |Douglas   |133-19-9920|Secretary, company         |2  |
|Morrow   |Alex      |533-54-4033|Town planner               |3  |
+---------+----------+-----------+---------------------------+---+
only showing top 20 rows

1917

## Part 4: Python Lambda functions and User Defined Functions
Python supports the use of small one-line anonymous functions that are not bound to a name at runtime.

`lambda` functions, borrowed from LISP, can be used wherever function objects are required. They are syntactically restricted to a single expression. Remember that `lambda` functions are a matter of style and using them is never required - semantically, they are just syntactic sugar for a normal function definition. You can always define a separate normal function instead, but using a `lambda` function is an equivalent and more compact form of coding. Ideally you should consider using `lambda` functions where you want to encapsulate non-reusable code without littering your code with one-line functions.

Here, instead of defining a separate function for the `filter()` transformation, we will use an inline `lambda()` function and we will register that lambda as a _Spark User Defined Function_ (UDF). A UDF is a special wrapper around a function, allowing the function to be used in a DataFrame query.

In [31]:
from pyspark.sql.types import BooleanType
from pyspark.sql.functions import udf
less_ten = udf(lambda s: s<10, BooleanType())
lambdaDF = subDF.filter(less_ten(subDF.age))
lambdaDF.show()
lambdaDF.count()

+---------+----------+-----------+--------------------+---+
|last_name|first_name|        ssn|          occupation|age|
+---------+----------+-----------+--------------------+---+
|    Pratt|  Kimberly|076-83-7404|        Sports coach|  9|
|    Evans|  Nicholas|711-43-1509|  Press photographer|  3|
|   Miller|     Tanya|867-83-8955|      Pharmacologist|  2|
|   Deleon|    Amanda|852-49-6969|Chief Operating O...|  7|
|    Lewis|     David|695-60-0033|  Field seismologist|  9|
|  Rodgers|   Beverly|819-57-7194|     Records manager|  0|
|  Johnson|    Amanda|494-58-8536|Higher education ...|  4|
|  Johnson|  Nicholas|157-13-2050|       IT consultant|  0|
|  Johnson|   Candice|639-80-6841| Electrical engineer|  6|
|    Arias|      Mark|501-67-7559|Management consul...|  4|
|    Jones|    Jeremy|648-72-8898|     Product manager|  8|
|  Delgado|     Sonia|283-58-4951|           Solicitor|  7|
| Robinson|      Adam|279-56-1630|   Financial manager|  1|
| Holloway|     Julia|115-33-9587|            Animator|  3|
|  Fleming|      Jodi|833-40-8181|Agricultural engi...|  0|
|   Powell|  Kimberly|102-37-5719|Contracting civil...|  6|
| Valencia|    Alicia|274-89-5763|Lecturer, further...|  6|
| Griffith|   Valerie|182-03-1388| Exhibition designer|  6|
|     Peck|   Douglas|133-19-9920|  Secretary, company|  2|
|   Morrow|      Alex|533-54-4033|        Town planner|  3|
+---------+----------+-----------+--------------------+---+
only showing top 20 rows

1917

In [32]:
# Let's collect the even values less than 10
even = udf(lambda s: s % 2 == 0, BooleanType())
evenDF = lambdaDF.filter(even(lambdaDF.age))
evenDF.show()
evenDF.count()

+---------+----------+-----------+--------------------+---+
|last_name|first_name|        ssn|          occupation|age|
+---------+----------+-----------+--------------------+---+
|   Miller|     Tanya|867-83-8955|      Pharmacologist|  2|
|  Rodgers|   Beverly|819-57-7194|     Records manager|  0|
|  Johnson|    Amanda|494-58-8536|Higher education ...|  4|
|  Johnson|  Nicholas|157-13-2050|       IT consultant|  0|
|  Johnson|   Candice|639-80-6841| Electrical engineer|  6|
|    Arias|      Mark|501-67-7559|Management consul...|  4|
|    Jones|    Jeremy|648-72-8898|     Product manager|  8|
|  Fleming|      Jodi|833-40-8181|Agricultural engi...|  0|
|   Powell|  Kimberly|102-37-5719|Contracting civil...|  6|
| Valencia|    Alicia|274-89-5763|Lecturer, further...|  6|
| Griffith|   Valerie|182-03-1388| Exhibition designer|  6|
|     Peck|   Douglas|133-19-9920|  Secretary, company|  2|
|    Meyer|  Cristian|602-45-1203|              Gaffer|  8|
| Gallegos|   Michael|203-15-1520|      Water engineer|  0|
|     King|Jacqueline|506-33-4081|        Risk manager|  2|
| Marshall|  Geoffrey|826-82-5735|Designer, fashion...|  2|
| Williams|    Nicole|574-72-0358|       Advice worker|  4|
|     Mack|   Bradley|662-80-6804|   Market researcher|  4|
|   Howard|  Nicholas|188-57-7205|          Astronomer|  8|
|    Smith|     Glenn|138-46-4267|English as a fore...|  4|
+---------+----------+-----------+--------------------+---+
only showing top 20 rows

879

## Part 5: Additional DataFrame actions
Let's investigate some additional actions:
* `first()`
* `take()`

One useful thing to do when we have a new dataset is to look at the first few entries to obtain a rough idea of what information is available. In Spark, we can do that using actions like `first()`, `take()`, and `show()`. Note that for the `first()` and `take()` actions, the elements that are returned depend on how the DataFrame is _partitioned_.

Instead of using the `collect()` action, we can use the `take(n)` action to return the first _n_ elements of the DataFrame. The `first()` action returns the first element of a DataFrame, and is equivalent to `take(1)[0]`.

In [33]:
print "first: {0}\n".format(filteredDF.first())
print "Four of them: {0}\n".format(filteredDF.take(4))

first: Row(last_name=u'Pratt', first_name=u'Kimberly', ssn=u'076-83-7404', occupation=u'Sports coach', age=9)

Four of them: [Row(last_name=u'Pratt', first_name=u'Kimberly', ssn=u'076-83-7404', occupation=u'Sports coach', age=9), Row(last_name=u'Evans', first_name=u'Nicholas', ssn=u'711-43-1509', occupation=u'Press photographer', age=3), Row(last_name=u'Miller', first_name=u'Tanya', ssn=u'867-83-8955', occupation=u'Pharmacologist', age=2), Row(last_name=u'Deleon', first_name=u'Amanda', ssn=u'852-49-6969', occupation=u'Chief Operating Officer', age=7)]

## Part 6: Additional DataFrame transformations

### (6a) `orderBy`
`orderBy()` allows you to sort a DataFrame by one or more columns, producing a new DataFrame.

For example, let's get the first five oldest people in the original (unfiltered) DataFrame. We can use the `orderBy()` transformation. `orderBy` takes one or more columns, either as names (strings) or as Column objects. To get a Column object, we use one of two notations on the DataFrame:
* Pandas-style notation: filteredDF.age
* Subscript notation: filteredDF['age']

Both of those syntaxes return a Column, which has additional methods like `desc()` (for sorting in descending order) or `asc()` (for sorting in ascending order, which is the default).

Here are some examples:
```python
dataDF.orderBy(dataDF['age'])  # sort by age in ascending order; returns a new DataFrame
dataDF.orderBy(dataDF.last_name.desc()) # sort by last name in descending order
```

In [34]:
# Get the five oldest people in the list. To do that, sort by age in descending order.
dataDF.orderBy(dataDF.age.desc()).show(5)

+---------+----------+-----------+--------------------+---+
|last_name|first_name|        ssn|          occupation|age|
+---------+----------+-----------+--------------------+---+
|     Lamb|   Kristen|343-69-4209| Medical illustrator| 48|
|  Escobar|    Dustin|367-01-3335|        Retail buyer| 48|
|  Wheeler|     Kelly|790-27-9149|        Nurse, adult| 48|
|  Sanchez|   Jeffrey|470-81-4511|Conservation offi...| 48|
|    Scott|   Rebecca|466-51-7906|      Pilot, airline| 48|
+---------+----------+-----------+--------------------+---+
only showing top 5 rows

Let's reverse the sort order. Since ascending sort is the default, we can actually use a Column object expression or a simple string, in this case. The `desc()` and `asc()` methods are only defined on `Column`. Something like `orderBy('age'.desc())` would not work, because there's no `desc()` method on Python string objects. That's why we needed the column expression. But if we're just using the defaults, we can pass a string column name into `orderBy()`. This is sometimes easier to read.

In [41]:
# Get the five oldest people in the list. To do that, sort by age in descending order.
dataDF.orderBy(dataDF.age.desc()).show(5)

+---------+----------+-----------+--------------------+---+
|last_name|first_name|        ssn|          occupation|age|
+---------+----------+-----------+--------------------+---+
|  Vazquez|     Angel|371-59-8543|       Media planner| 48|
|     Gill|     Debra|308-81-5452|Administrator, Ci...| 48|
|  Aguirre|  Cristian|035-66-0540| Surveyor, insurance| 48|
| Williams|   Patrick|812-88-9795|  Professor Emeritus| 48|
|    Brown|   Richard|766-97-3117|Water quality sci...| 48|
+---------+----------+-----------+--------------------+---+
only showing top 5 rows

## (6b) `distinct()` and `dropDuplicates()`
`distinct()` filters out duplicate rows, and it considers all columns. Since our data is completely randomly generated (by `fake-factory`), it's extremely unlikely that there are any duplicate rows:

In [42]:
print(dataDF.count())
print(dataDF.distinct().count())

10000
10000

To demonstrate distinct(), let's create a quick throwaway dataset.

In [43]:
# A dummy DataFrame with duplicated entries.
tempDF = sqlContext.createDataFrame([("Joe", 1), ("Joe", 1), ("Anna", 15), ("Anna", 12), ("Ravi", 5)], ('name', 'score'))
# Original DataFrame
tempDF.show()
# Distinct DataFrame
tempDF.distinct().show()

+----+-----+
|name|score|
+----+-----+
| Joe|    1|
| Joe|    1|
|Anna|   15|
|Anna|   12|
|Ravi|    5|
+----+-----+

+----+-----+
|name|score|
+----+-----+
| Joe|    1|
|Ravi|    5|
|Anna|   12|
|Anna|   15|
+----+-----+

Note that one of the ("Joe", 1) rows was deleted, but both rows with name "Anna" were kept, because all columns in a row must match another row for it to be considered a duplicate.

`dropDuplicates()` is like `distinct()`, except that it allows us to specify the columns to compare. For instance, we can use it to drop all rows where the first name and last name duplicates (ignoring the occupation and age columns).

In [44]:
print(tempDF.count())
print(tempDF.dropDuplicates(['name']).count())
tempDF.dropDuplicates(['name']).show()

5
3
+----+-----+
|name|score|
+----+-----+
| Joe|    1|
|Ravi|    5|
|Anna|   15|
+----+-----+

### (6c) `drop()`
`drop()` is like the opposite of `select()`: Instead of selecting specific columns from a DataFrame, it drops a specifed column from a DataFrame.

Here's a simple use case: Suppose you're reading from a 1,000-column CSV file, and you have to get rid of five of the columns. Instead of selecting 995 of the columns, it's easier just to drop the five you don't want.

In [45]:
dataDF.drop('occupation').drop('age').show()

+---------+----------+-----------+
|last_name|first_name|        ssn|
+---------+----------+-----------+
|    Stein|     Jacob|039-19-0531|
| Hamilton|     Tommy|824-45-1140|
|  Chapman|   Deborah|735-56-4346|
|    Moody|     David|382-11-7793|
|  Oconnor|   Michael|356-45-3733|
|   Dudley|    Steven|087-09-9992|
|     Rice|     Derek|048-55-3413|
|    Pratt|  Kimberly|076-83-7404|
|   Norton|      Ryan|504-17-8123|
|   Taylor|   Cynthia|436-83-3006|
|   Nguyen|      Gary|194-03-8285|
| Williams|   Barbara|206-33-1107|
|  Shaffer|     Danny|554-12-0804|
|    Evans|  Nicholas|711-43-1509|
|   Miller|     Tanya|867-83-8955|
|    Jones|     Robin|796-17-7156|
|  Holland|    Hannah|249-01-5612|
|Patterson|     Bobby|056-60-8511|
|   Powell|     Tammy|850-80-0231|
|Patterson|    Andrew|354-55-4587|
+---------+----------+-----------+
only showing top 20 rows

### (6d) `groupBy()`
`groupBy()` is one of the most powerful transformations. It allows you to perform aggregations on a DataFrame.

Unlike other DataFrame transformations, `groupBy()` does not return a DataFrame. Instead, it returns a special GroupedData object that contains various aggregation functions.

The most commonly used aggregation function is `count()`, but there are others (like `sum()`, `max()`, and `avg()`.
These aggregation functions typically create a new column and return a new DataFrame..

In [46]:
# Count total number of people of each occupation.
dataDF.groupBy('occupation').count().show(truncate=False)

+---------------------------------------+-----+
|occupation                             |count|
+---------------------------------------+-----+
|Librarian, academic                    |18   |
|Catering manager                       |23   |
|Retail merchandiser                    |14   |
|Designer, ceramics/pottery             |18   |
|Engineer, aeronautical                 |11   |
|Diplomatic Services operational officer|15   |
|English as a second language teacher   |20   |
|Early years teacher                    |17   |
|Occupational hygienist                 |16   |
|Patent examiner                        |12   |
|Primary school teacher                 |14   |
|Clinical molecular geneticist          |17   |
|Control and instrumentation engineer   |18   |
|Estate agent                           |19   |
|Art therapist                          |13   |
|Transport planner                      |21   |
|Applications developer                 |19   |
|Petroleum engineer                     |23   |
|Adult nurse                            |24   |
|Conservator, furniture                 |9    |
+---------------------------------------+-----+
only showing top 20 rows

In [47]:
# Compute average age.
dataDF.groupBy().avg('age').show(truncate=False)

+--------+
|avg(age)|
+--------+
|24.9736 |
+--------+

In [48]:
# Compute max and min ages.
print('Maximum age: {0}'.format(dataDF.groupBy().max('age').first()[0]))
print('Minimum age: {0}'.format(dataDF.groupBy().min('age').first()[0]))

Maximum age: 48
Minimum age: 1

### (6e) `sample()`
When analyzing data, the `sample()` transformation is often quite useful. It returns a new DataFrame with a random sample of elements from the dataset. It takes in a `withReplacement` argument, which specifies whether it is okay to randomly pick the same item multiple times from the parent DataFrame (so when `withReplacement=True`, you can get the same item back multiple times). It takes in a `fraction` parameter, which specifies the fraction elements in the dataset you want to return. (So a `fraction` value of `0.20` returns 20% of the elements in the DataFrame.) It also takes an optional `seed` parameter that allows you to specify a seed value for the random number generator, so that reproducible results can be obtained.

In [49]:
sampledDF = dataDF.sample(withReplacement=False, fraction=0.10)
print(sampledDF.count())
sampledDF.show()

1029
+---------+----------+-----------+--------------------+---+
|last_name|first_name|        ssn|          occupation|age|
+---------+----------+-----------+--------------------+---+
| Thompson|     Terri|607-24-8694|   Food technologist| 34|
|   Walker|    Joseph|079-99-5775|Restaurant manage...| 30|
|    David|     Tracy|384-34-4827|              Lawyer| 39|
|     Cook|   Jessica|811-23-6545|        Town planner| 25|
|    Perez| Elizabeth|571-87-0459|        Sports coach| 44|
|   Miller|     Jacob|691-69-2880|      Chief of Staff| 30|
|    Davis|    Briana|687-12-3800|Research officer,...| 26|
|    Moore|     Scott|514-35-9041|Public house manager| 26|
|   Hughes|       Amy|255-17-3490|   Chemical engineer| 11|
|Rodriguez|    Donald|873-75-1255|Research scientis...| 40|
|   Horton|   Dominic|057-78-9985|   Food technologist| 18|
|     Page|     Keith|654-17-6677|Armed forces tech...| 27|
|    Riggs|   Brianna|320-57-4634|Licensed conveyancer| 32|
|  Krueger|   Allison|290-22-8699| Production engineer| 21|
|    Lewis|Jacqueline|041-54-8809|    Product designer| 35|
|  Rodgers|     Kelly|432-48-2206|Local government ...| 22|
| Lawrence|     Brett|752-13-1070|       Airline pilot| 24|
|    Mills|     Louis|803-99-8901|        Sports coach| 20|
|  Johnson|    Walter|539-13-8003|Chartered managem...| 21|
| Reynolds|    Meagan|294-76-0379|           Ecologist| 20|
+---------+----------+-----------+--------------------+---+
only showing top 20 rows

In [50]:
print(dataDF.sample(withReplacement=False,fraction=0.05).count())

500

## Part 7: Caching DataFrames and storage options

### (7a) Caching DataFrames
For efficiency Spark keeps your DataFrames in memory. (More formally, it keeps the RDDs that implement your DataFrames in memory.) By keeping the contents in memory, Spark can quickly access the data. However, memory is limited, so if you try to keep too many partitions in memory, Spark will automatically delete partitions from memory to make space for new ones. If you later refer to one of the deleted partitions, Spark will automatically recreate it for you, but that takes time.

So, if you plan to use a DataFrame more than once, then you should tell Spark to cache it. You can use the `cache()` operation to keep the DataFrame in memory. However, you must still trigger an action on the DataFrame, such as `collect()` or `count()` before the caching will occur. In other words, `cache()` is lazy: It merely tells Spark that the DataFrame should be cached when the data is materialized. You have to run an action to materialize the data; the DataFrame will be cached as a side effect. The next time you use the DataFrame, Spark will use the cached data, rather than recomputing the DataFrame from the original data.

You can see your cached DataFrame in the "Storage" section of the Spark web UI. If you click on the name value, you can see more information about where the the DataFrame is stored.

In [51]:
# Cache the DataFrame
filteredDF.cache()
# Trigger an action
print filteredDF.count()
# Check if it is cached
print filteredDF.is_cached

1916
True

### (7b) Unpersist and storage options

Spark automatically manages the partitions cached in memory. If it has more partitions than available memory, by default, it will evict older partitions to make room for new ones. For efficiency, once you are finished using cached DataFrame, you can optionally tell Spark to stop caching it in memory by using the DataFrame's `unpersist()` method to inform Spark that you no longer need the cached data.

Advanced: Spark provides many more options for managing how DataFrames cached. For instance, you can tell Spark to spill cached partitions to disk when it runs out of memory, instead of simply throwing old ones away. You can explore the API for DataFrame's `persist()` operation using Python's `help()` command. The `persist()` operation, optionally, takes a pySpark [StorageLevel](http://spark.apache.org/docs/latest/api/python/pyspark.html#pyspark.StorageLevel) object.

In [52]:
# If we are done with the DataFrame we can unpersist it so that its memory can be reclaimed
filteredDF.unpersist()
# Check if it is cached
print filteredDF.is_cached

False

## Part 8: Debugging Spark applications and lazy evaluation
### How Python is Executed in Spark
Internally, Spark executes using a Java Virtual Machine (JVM). pySpark runs Python code in a JVM using Py4J. Py4J enables Python programs running in a Python interpreter to dynamically access Java objects in a Java Virtual Machine. Methods are called as if the Java objects resided in the Python interpreter and Java collections can be accessed through standard Python collection methods. Py4J also enables Java programs to call back Python objects.

Because pySpark uses Py4J, coding errors often result in a complicated, confusing stack trace that can be difficult to understand. In the following section, we'll explore how to understand stack traces.

### (8a) Challenges with lazy evalutaion using transformations and actions

Spark's use of lazy evaluation can make debugging more difficult because code is not always executed immediately. To see an example of how this can happen, let's first define a broken filter function. Next we perform a `filter()` operation using the broken filtering function. No error will occur at this point due to Spark's use of lazy evaluation.

The `filter()` method will not be executed _until_ an action operation is invoked on the DataFrame. We will perform an action by using the `collect()` method to return a list that contains all of the elements in this DataFrame.

In [55]:
def brokenTen(value):
    ''' Check whether a variable is less than ten.
    Input:
        value: the value to be compared with ten
    Output: 
        boolean: True if value < 10 else False
    Note:
        In if statement the variable val is undefined, which will throw an error.
    
    '''
    if (value < 10):
        return True
    else:
        return False

btUDF = udf(brokenTen)
brokenDF = subDF.filter(btUDF(subDF.age)==True)

When an action is called on the DataFrame, `brokenTen` function will be called and an error will occur.

In [56]:
# Now we'll see the error
brokenDF.count()

0

### (8b) Finding the bug
When the `filter()` method is executed, Spark calls the UDF. Since our UDF has an error in the underlying filtering function `brokenTen()`, an error occurs.

Scroll through the output "Py4JJavaError Traceback (most recent call last)" part of the cell and first you will see that the line that generated the error is the `collect()` method line. There is nothing wrong with this line. However, it is an action and that caused other methods to be executed. Continue scrolling through the Traceback and you will see the following error line:

`NameError: global name 'val' is not defined`

Looking at this error line, we can see that we used the wrong variable name in our filtering function `brokenTen()`.

### (8c) Moving toward expert style
As you are learning Spark, I recommend that you write your code in the form:

    df2 = df1.transformation1()
    df2.action1()
    df3 = df2.transformation2()
    df3.action2()
    
Using this style will make debugging your code much easier as it makes errors easier to localize - errors in your transformations will occur when the next action is executed.

Once you become more experienced with Spark, you can write your code with the form:

    df.transformation1().transformation2().action()

We can also use `lambda()` functions instead of separately defined functions when their use improves readability and conciseness.

In [57]:
# Cleaner code through lambda use
myUDF = udf(lambda v: v < 10, BooleanType())
subDF.filter(myUDF(subDF.age) == True).show(truncate=False)

+---------+----------+-----------+---------------------------+---+
|last_name|first_name|ssn        |occupation                 |age|
+---------+----------+-----------+---------------------------+---+
|Pratt    |Kimberly  |076-83-7404|Sports coach               |9  |
|Evans    |Nicholas  |711-43-1509|Press photographer         |3  |
|Miller   |Tanya     |867-83-8955|Pharmacologist             |2  |
|Deleon   |Amanda    |852-49-6969|Chief Operating Officer    |7  |
|Lewis    |David     |695-60-0033|Field seismologist         |9  |
|Rodgers  |Beverly   |819-57-7194|Records manager            |0  |
|Johnson  |Amanda    |494-58-8536|Higher education lecturer  |4  |
|Johnson  |Nicholas  |157-13-2050|IT consultant              |0  |
|Johnson  |Candice   |639-80-6841|Electrical engineer        |6  |
|Arias    |Mark      |501-67-7559|Management consultant      |4  |
|Jones    |Jeremy    |648-72-8898|Product manager            |8  |
|Delgado  |Sonia     |283-58-4951|Solicitor                  |7  |
|Robinson |Adam      |279-56-1630|Financial manager          |1  |
|Holloway |Julia     |115-33-9587|Animator                   |3  |
|Fleming  |Jodi      |833-40-8181|Agricultural engineer      |0  |
|Powell   |Kimberly  |102-37-5719|Contracting civil engineer |6  |
|Valencia |Alicia    |274-89-5763|Lecturer, further education|6  |
|Griffith |Valerie   |182-03-1388|Exhibition designer        |6  |
|Peck     |Douglas   |133-19-9920|Secretary, company         |2  |
|Morrow   |Alex      |533-54-4033|Town planner               |3  |
+---------+----------+-----------+---------------------------+---+
only showing top 20 rows

### (8d) Readability and code style
To make the expert coding style more readable, enclose the statement in parentheses and put each method, transformation, or action on a separate line.

In [58]:
# Final version
from pyspark.sql.functions import *
(dataDF
    .filter(dataDF.age > 20)
    .select(concat(dataDF.first_name, lit(' '), dataDF.last_name), dataDF.occupation)
    .show(truncate=False)
)

+--------------------------------+-----------------------------+
|concat(first_name,  , last_name)|occupation                   |
+--------------------------------+-----------------------------+
|Tommy Hamilton                  |Chief Operating Officer      |
|David Moody                     |Designer, multimedia         |
|Michael Oconnor                 |Paediatric nurse             |
|Steven Dudley                   |Nurse, adult                 |
|Derek Rice                      |Brewing technologist         |
|Ryan Norton                     |Surveyor, mining             |
|Gary Nguyen                     |Forensic scientist           |
|Barbara Williams                |Insurance risk surveyor      |
|Danny Shaffer                   |Bookseller                   |
|Hannah Holland                  |Public house manager         |
|Bobby Patterson                 |Statistician                 |
|Andrew Patterson                |Radio broadcast assistant    |
|Michelle Johns                  |Health service manager       |
|Jennifer Mcdowell               |Education officer, museum    |
|Anna Mejia                      |Designer, television/film set|
|David Shaw                      |Production manager           |
|Victoria Paul                   |Environmental manager        |
|Jeff Hays                       |Music tutor                  |
|Erica Nguyen                    |Agricultural engineer        |
|Christopher Skinner             |Operational investment banker|
+--------------------------------+-----------------------------+
only showing top 20 rows

In [59]:
from pyspark.sql.types import *
time_data = [('1995-08-01 00:00:14.0',), ('1995-08-03 00:00:14.0',), ('1995-08-02 00:00:14.0',)]

schema = StructType([StructField("Time", StringType(), True)])
df = sqlContext.createDataFrame(time_data, schema)
df.show()

+--------------------+
|                Time|
+--------------------+
|1995-08-01 00:00:...|
|1995-08-03 00:00:...|
|1995-08-02 00:00:...|
+--------------------+